// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace PKVault.Backend.Migrations
{
    [DbContext(typeof(SessionDbContext))]
    [Migration("20260203021248_AddDexLanguages")]
    partial class AddDexLanguages
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.2");

            modelBuilder.Entity("BankEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("IdInt")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<string>("View")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Banks");
                });

            modelBuilder.Entity("BoxEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("BankId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("IdInt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SlotCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BankId");

                    b.ToTable("Boxes");
                });

            modelBuilder.Entity("DexFormEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<byte>("Form")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("Gender")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsCaught")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsCaughtShiny")
                        .HasColumnType("INTEGER");

                    b.PrimitiveCollection<string>("Languages")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<ushort>("Species")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Form");

                    b.HasIndex("Gender");

                    b.HasIndex("Species");

                    b.ToTable("Pokedex");
                });

            modelBuilder.Entity("PkmFileEntity", b =>
                {
                    b.Property<string>("Filepath")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Data")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<bool>("Deleted")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Error")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Updated")
                        .HasColumnType("INTEGER");

                    b.HasKey("Filepath");

                    b.ToTable("PkmFiles");
                });

            modelBuilder.Entity("PkmVariantEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<uint?>("AttachedSaveId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AttachedSavePkmIdBase")
                        .HasColumnType("TEXT");

                    b.Property<string>("BoxId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("BoxSlot")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Filepath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte>("Form")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("Gender")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("Generation")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsMain")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsShiny")
                        .HasColumnType("INTEGER");

                    b.Property<ushort>("Species")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AttachedSaveId")
                        .HasFilter("AttachedSaveId IS NOT NULL");

                    b.HasIndex("BoxId");

                    b.HasIndex("Filepath")
                        .IsUnique();

                    b.HasIndex("AttachedSaveId", "AttachedSavePkmIdBase")
                        .HasFilter("AttachedSaveId IS NOT NULL");

                    b.HasIndex("BoxId", "BoxSlot");

                    b.HasIndex("Species", "Form", "Gender");

                    b.HasIndex("Species", "Form", "Gender", "IsShiny");

                    b.ToTable("PkmVersions");
                });

            modelBuilder.Entity("BoxEntity", b =>
                {
                    b.HasOne("BankEntity", null)
                        .WithMany()
                        .HasForeignKey("BankId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PkmVariantEntity", b =>
                {
                    b.HasOne("BoxEntity", null)
                        .WithMany()
                        .HasForeignKey("BoxId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PkmFileEntity", "PkmFile")
                        .WithOne()
                        .HasForeignKey("PkmVariantEntity", "Filepath")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("PkmFile");
                });
#pragma warning restore 612, 618
        }
    }
}
