/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * PKVault API
 * OpenAPI spec version: 1.0.0
 */
import { useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  StaticDataDTO,
  StaticDataGetSpritesheetImgParams,
} from "../model";

import { customInstance } from "../../mutator/custom-instance";
import type { ErrorType } from "../../mutator/custom-instance";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export type staticDataGetResponse200TextPlain = {
  data: StaticDataDTO;
  status: 200;
};

export type staticDataGetResponse200ApplicationJson = {
  data: StaticDataDTO;
  status: 200;
};

export type staticDataGetResponse200TextJson = {
  data: StaticDataDTO;
  status: 200;
};

export type staticDataGetResponseSuccess = (
  | staticDataGetResponse200TextPlain
  | staticDataGetResponse200ApplicationJson
  | staticDataGetResponse200TextJson
) & {
  headers: Headers;
};
export const getStaticDataGetUrl = () => {
  return `/api/static-data`;
};

export const staticDataGet = async (
  options?: RequestInit,
): Promise<staticDataGetResponseSuccess> => {
  return customInstance<staticDataGetResponseSuccess>(getStaticDataGetUrl(), {
    ...options,
    method: "GET",
  });
};

export const getStaticDataGetQueryKey = () => {
  return [`/api/static-data`] as const;
};

export const getStaticDataGetQueryOptions = <
  TData = Awaited<ReturnType<typeof staticDataGet>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof staticDataGet>>, TError, TData>
  >;
  request?: SecondParameter<typeof customInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getStaticDataGetQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof staticDataGet>>> = ({
    signal,
  }) => staticDataGet({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof staticDataGet>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type StaticDataGetQueryResult = NonNullable<
  Awaited<ReturnType<typeof staticDataGet>>
>;
export type StaticDataGetQueryError = ErrorType<unknown>;

export function useStaticDataGet<
  TData = Awaited<ReturnType<typeof staticDataGet>>,
  TError = ErrorType<unknown>,
>(
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof staticDataGet>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof staticDataGet>>,
          TError,
          Awaited<ReturnType<typeof staticDataGet>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useStaticDataGet<
  TData = Awaited<ReturnType<typeof staticDataGet>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof staticDataGet>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof staticDataGet>>,
          TError,
          Awaited<ReturnType<typeof staticDataGet>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useStaticDataGet<
  TData = Awaited<ReturnType<typeof staticDataGet>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof staticDataGet>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useStaticDataGet<
  TData = Awaited<ReturnType<typeof staticDataGet>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof staticDataGet>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getStaticDataGetQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

export type staticDataGetSpritesheetImgResponse200 = {
  data: Blob;
  status: 200;
};

export type staticDataGetSpritesheetImgResponseSuccess =
  staticDataGetSpritesheetImgResponse200 & {
    headers: Headers;
  };
export const getStaticDataGetSpritesheetImgUrl = (
  sheetName: string,
  params?: StaticDataGetSpritesheetImgParams,
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/static-data/spritesheet/${sheetName}?${stringifiedParams}`
    : `/api/static-data/spritesheet/${sheetName}`;
};

export const staticDataGetSpritesheetImg = async (
  sheetName: string,
  params?: StaticDataGetSpritesheetImgParams,
  options?: RequestInit,
): Promise<staticDataGetSpritesheetImgResponseSuccess> => {
  return customInstance<staticDataGetSpritesheetImgResponseSuccess>(
    getStaticDataGetSpritesheetImgUrl(sheetName, params),
    {
      ...options,
      method: "GET",
    },
  );
};

export const getStaticDataGetSpritesheetImgQueryKey = (
  sheetName: string,
  params?: StaticDataGetSpritesheetImgParams,
) => {
  return [
    `/api/static-data/spritesheet/${sheetName}`,
    ...(params ? [params] : []),
  ] as const;
};

export const getStaticDataGetSpritesheetImgQueryOptions = <
  TData = Awaited<ReturnType<typeof staticDataGetSpritesheetImg>>,
  TError = ErrorType<unknown>,
>(
  sheetName: string,
  params?: StaticDataGetSpritesheetImgParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof staticDataGetSpritesheetImg>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getStaticDataGetSpritesheetImgQueryKey(sheetName, params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof staticDataGetSpritesheetImg>>
  > = ({ signal }) =>
    staticDataGetSpritesheetImg(sheetName, params, {
      signal,
      ...requestOptions,
    });

  return {
    queryKey,
    queryFn,
    enabled: !!sheetName,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof staticDataGetSpritesheetImg>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type StaticDataGetSpritesheetImgQueryResult = NonNullable<
  Awaited<ReturnType<typeof staticDataGetSpritesheetImg>>
>;
export type StaticDataGetSpritesheetImgQueryError = ErrorType<unknown>;

export function useStaticDataGetSpritesheetImg<
  TData = Awaited<ReturnType<typeof staticDataGetSpritesheetImg>>,
  TError = ErrorType<unknown>,
>(
  sheetName: string,
  params: undefined | StaticDataGetSpritesheetImgParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof staticDataGetSpritesheetImg>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof staticDataGetSpritesheetImg>>,
          TError,
          Awaited<ReturnType<typeof staticDataGetSpritesheetImg>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useStaticDataGetSpritesheetImg<
  TData = Awaited<ReturnType<typeof staticDataGetSpritesheetImg>>,
  TError = ErrorType<unknown>,
>(
  sheetName: string,
  params?: StaticDataGetSpritesheetImgParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof staticDataGetSpritesheetImg>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof staticDataGetSpritesheetImg>>,
          TError,
          Awaited<ReturnType<typeof staticDataGetSpritesheetImg>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useStaticDataGetSpritesheetImg<
  TData = Awaited<ReturnType<typeof staticDataGetSpritesheetImg>>,
  TError = ErrorType<unknown>,
>(
  sheetName: string,
  params?: StaticDataGetSpritesheetImgParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof staticDataGetSpritesheetImg>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useStaticDataGetSpritesheetImg<
  TData = Awaited<ReturnType<typeof staticDataGetSpritesheetImg>>,
  TError = ErrorType<unknown>,
>(
  sheetName: string,
  params?: StaticDataGetSpritesheetImgParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof staticDataGetSpritesheetImg>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getStaticDataGetSpritesheetImgQueryOptions(
    sheetName,
    params,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}
