/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * PKVault API
 * OpenAPI spec version: 1.0.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  BankDTO,
  BankView,
  BoxDTO,
  DataActionPayload,
  DataDTO,
  EditPkmVariantPayload,
  MoveItem,
  PkmSaveDTO,
  PkmVariantDTO,
  StorageCreateMainBoxParams,
  StorageDeleteActionsParams,
  StorageDexSyncParams,
  StorageEvolvePkmsParams,
  StorageGetBoxesParams,
  StorageGetPkmAvailableMovesParams,
  StorageGetPkmsLegality200One,
  StorageGetPkmsLegality200Three,
  StorageGetPkmsLegality200Two,
  StorageGetPkmsLegalityParams,
  StorageMainCreatePkmVariantParams,
  StorageMainDeletePkmVariantParams,
  StorageMainPkmDetachSaveParams,
  StorageMovePkmBankParams,
  StorageMovePkmParams,
  StorageSaveDeletePkmsParams,
  StorageSortPkmsParams,
  StorageUpdateMainBankParams,
  StorageUpdateMainBoxParams,
} from "../model";

import { customInstance } from "../../mutator/custom-instance";
import type { ErrorType } from "../../mutator/custom-instance";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export type storageGetMainBanksResponse200TextPlain = {
  data: BankDTO[];
  status: 200;
};

export type storageGetMainBanksResponse200ApplicationJson = {
  data: BankDTO[];
  status: 200;
};

export type storageGetMainBanksResponse200TextJson = {
  data: BankDTO[];
  status: 200;
};

export type storageGetMainBanksResponseSuccess = (
  | storageGetMainBanksResponse200TextPlain
  | storageGetMainBanksResponse200ApplicationJson
  | storageGetMainBanksResponse200TextJson
) & {
  headers: Headers;
};
export const getStorageGetMainBanksUrl = () => {
  return `/api/storage/main/bank`;
};

export const storageGetMainBanks = async (
  options?: RequestInit,
): Promise<storageGetMainBanksResponseSuccess> => {
  return customInstance<storageGetMainBanksResponseSuccess>(
    getStorageGetMainBanksUrl(),
    {
      ...options,
      method: "GET",
    },
  );
};

export const getStorageGetMainBanksQueryKey = () => {
  return [`/api/storage/main/bank`] as const;
};

export const getStorageGetMainBanksQueryOptions = <
  TData = Awaited<ReturnType<typeof storageGetMainBanks>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof storageGetMainBanks>>,
      TError,
      TData
    >
  >;
  request?: SecondParameter<typeof customInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getStorageGetMainBanksQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof storageGetMainBanks>>
  > = ({ signal }) => storageGetMainBanks({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof storageGetMainBanks>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type StorageGetMainBanksQueryResult = NonNullable<
  Awaited<ReturnType<typeof storageGetMainBanks>>
>;
export type StorageGetMainBanksQueryError = ErrorType<unknown>;

export function useStorageGetMainBanks<
  TData = Awaited<ReturnType<typeof storageGetMainBanks>>,
  TError = ErrorType<unknown>,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof storageGetMainBanks>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof storageGetMainBanks>>,
          TError,
          Awaited<ReturnType<typeof storageGetMainBanks>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useStorageGetMainBanks<
  TData = Awaited<ReturnType<typeof storageGetMainBanks>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof storageGetMainBanks>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof storageGetMainBanks>>,
          TError,
          Awaited<ReturnType<typeof storageGetMainBanks>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useStorageGetMainBanks<
  TData = Awaited<ReturnType<typeof storageGetMainBanks>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof storageGetMainBanks>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useStorageGetMainBanks<
  TData = Awaited<ReturnType<typeof storageGetMainBanks>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof storageGetMainBanks>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getStorageGetMainBanksQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

export type storageCreateMainBankResponse200TextPlain = {
  data: DataDTO;
  status: 200;
};

export type storageCreateMainBankResponse200ApplicationJson = {
  data: DataDTO;
  status: 200;
};

export type storageCreateMainBankResponse200TextJson = {
  data: DataDTO;
  status: 200;
};

export type storageCreateMainBankResponseSuccess = (
  | storageCreateMainBankResponse200TextPlain
  | storageCreateMainBankResponse200ApplicationJson
  | storageCreateMainBankResponse200TextJson
) & {
  headers: Headers;
};
export const getStorageCreateMainBankUrl = () => {
  return `/api/storage/main/bank`;
};

export const storageCreateMainBank = async (
  options?: RequestInit,
): Promise<storageCreateMainBankResponseSuccess> => {
  return customInstance<storageCreateMainBankResponseSuccess>(
    getStorageCreateMainBankUrl(),
    {
      ...options,
      method: "POST",
    },
  );
};

export const getStorageCreateMainBankMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof storageCreateMainBank>>,
    TError,
    void,
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof storageCreateMainBank>>,
  TError,
  void,
  TContext
> => {
  const mutationKey = ["storageCreateMainBank"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof storageCreateMainBank>>,
    void
  > = () => {
    return storageCreateMainBank(requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type StorageCreateMainBankMutationResult = NonNullable<
  Awaited<ReturnType<typeof storageCreateMainBank>>
>;

export type StorageCreateMainBankMutationError = ErrorType<unknown>;

export const useStorageCreateMainBank = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof storageCreateMainBank>>,
      TError,
      void,
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof storageCreateMainBank>>,
  TError,
  void,
  TContext
> => {
  return useMutation(
    getStorageCreateMainBankMutationOptions(options),
    queryClient,
  );
};
export type storageGetMainPkmVariantsResponse200TextPlain = {
  data: PkmVariantDTO[];
  status: 200;
};

export type storageGetMainPkmVariantsResponse200ApplicationJson = {
  data: PkmVariantDTO[];
  status: 200;
};

export type storageGetMainPkmVariantsResponse200TextJson = {
  data: PkmVariantDTO[];
  status: 200;
};

export type storageGetMainPkmVariantsResponseSuccess = (
  | storageGetMainPkmVariantsResponse200TextPlain
  | storageGetMainPkmVariantsResponse200ApplicationJson
  | storageGetMainPkmVariantsResponse200TextJson
) & {
  headers: Headers;
};
export const getStorageGetMainPkmVariantsUrl = () => {
  return `/api/storage/main/pkm-version`;
};

export const storageGetMainPkmVariants = async (
  options?: RequestInit,
): Promise<storageGetMainPkmVariantsResponseSuccess> => {
  return customInstance<storageGetMainPkmVariantsResponseSuccess>(
    getStorageGetMainPkmVariantsUrl(),
    {
      ...options,
      method: "GET",
    },
  );
};

export const getStorageGetMainPkmVariantsQueryKey = () => {
  return [`/api/storage/main/pkm-version`] as const;
};

export const getStorageGetMainPkmVariantsQueryOptions = <
  TData = Awaited<ReturnType<typeof storageGetMainPkmVariants>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof storageGetMainPkmVariants>>,
      TError,
      TData
    >
  >;
  request?: SecondParameter<typeof customInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getStorageGetMainPkmVariantsQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof storageGetMainPkmVariants>>
  > = ({ signal }) => storageGetMainPkmVariants({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof storageGetMainPkmVariants>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type StorageGetMainPkmVariantsQueryResult = NonNullable<
  Awaited<ReturnType<typeof storageGetMainPkmVariants>>
>;
export type StorageGetMainPkmVariantsQueryError = ErrorType<unknown>;

export function useStorageGetMainPkmVariants<
  TData = Awaited<ReturnType<typeof storageGetMainPkmVariants>>,
  TError = ErrorType<unknown>,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof storageGetMainPkmVariants>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof storageGetMainPkmVariants>>,
          TError,
          Awaited<ReturnType<typeof storageGetMainPkmVariants>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useStorageGetMainPkmVariants<
  TData = Awaited<ReturnType<typeof storageGetMainPkmVariants>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof storageGetMainPkmVariants>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof storageGetMainPkmVariants>>,
          TError,
          Awaited<ReturnType<typeof storageGetMainPkmVariants>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useStorageGetMainPkmVariants<
  TData = Awaited<ReturnType<typeof storageGetMainPkmVariants>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof storageGetMainPkmVariants>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useStorageGetMainPkmVariants<
  TData = Awaited<ReturnType<typeof storageGetMainPkmVariants>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof storageGetMainPkmVariants>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getStorageGetMainPkmVariantsQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

export type storageMainCreatePkmVariantResponse200TextPlain = {
  data: DataDTO;
  status: 200;
};

export type storageMainCreatePkmVariantResponse200ApplicationJson = {
  data: DataDTO;
  status: 200;
};

export type storageMainCreatePkmVariantResponse200TextJson = {
  data: DataDTO;
  status: 200;
};

export type storageMainCreatePkmVariantResponseSuccess = (
  | storageMainCreatePkmVariantResponse200TextPlain
  | storageMainCreatePkmVariantResponse200ApplicationJson
  | storageMainCreatePkmVariantResponse200TextJson
) & {
  headers: Headers;
};
export const getStorageMainCreatePkmVariantUrl = (
  params: StorageMainCreatePkmVariantParams,
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/storage/main/pkm-version?${stringifiedParams}`
    : `/api/storage/main/pkm-version`;
};

export const storageMainCreatePkmVariant = async (
  params: StorageMainCreatePkmVariantParams,
  options?: RequestInit,
): Promise<storageMainCreatePkmVariantResponseSuccess> => {
  return customInstance<storageMainCreatePkmVariantResponseSuccess>(
    getStorageMainCreatePkmVariantUrl(params),
    {
      ...options,
      method: "POST",
    },
  );
};

export const getStorageMainCreatePkmVariantMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof storageMainCreatePkmVariant>>,
    TError,
    { params: StorageMainCreatePkmVariantParams },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof storageMainCreatePkmVariant>>,
  TError,
  { params: StorageMainCreatePkmVariantParams },
  TContext
> => {
  const mutationKey = ["storageMainCreatePkmVariant"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof storageMainCreatePkmVariant>>,
    { params: StorageMainCreatePkmVariantParams }
  > = (props) => {
    const { params } = props ?? {};

    return storageMainCreatePkmVariant(params, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type StorageMainCreatePkmVariantMutationResult = NonNullable<
  Awaited<ReturnType<typeof storageMainCreatePkmVariant>>
>;

export type StorageMainCreatePkmVariantMutationError = ErrorType<unknown>;

export const useStorageMainCreatePkmVariant = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof storageMainCreatePkmVariant>>,
      TError,
      { params: StorageMainCreatePkmVariantParams },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof storageMainCreatePkmVariant>>,
  TError,
  { params: StorageMainCreatePkmVariantParams },
  TContext
> => {
  return useMutation(
    getStorageMainCreatePkmVariantMutationOptions(options),
    queryClient,
  );
};
export type storageMainDeletePkmVariantResponse200TextPlain = {
  data: DataDTO;
  status: 200;
};

export type storageMainDeletePkmVariantResponse200ApplicationJson = {
  data: DataDTO;
  status: 200;
};

export type storageMainDeletePkmVariantResponse200TextJson = {
  data: DataDTO;
  status: 200;
};

export type storageMainDeletePkmVariantResponseSuccess = (
  | storageMainDeletePkmVariantResponse200TextPlain
  | storageMainDeletePkmVariantResponse200ApplicationJson
  | storageMainDeletePkmVariantResponse200TextJson
) & {
  headers: Headers;
};
export const getStorageMainDeletePkmVariantUrl = (
  params?: StorageMainDeletePkmVariantParams,
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    const explodeParameters = ["pkmVariantIds"];

    if (Array.isArray(value) && explodeParameters.includes(key)) {
      value.forEach((v) => {
        normalizedParams.append(key, v === null ? "null" : v.toString());
      });
      return;
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/storage/main/pkm-version?${stringifiedParams}`
    : `/api/storage/main/pkm-version`;
};

export const storageMainDeletePkmVariant = async (
  params?: StorageMainDeletePkmVariantParams,
  options?: RequestInit,
): Promise<storageMainDeletePkmVariantResponseSuccess> => {
  return customInstance<storageMainDeletePkmVariantResponseSuccess>(
    getStorageMainDeletePkmVariantUrl(params),
    {
      ...options,
      method: "DELETE",
    },
  );
};

export const getStorageMainDeletePkmVariantMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof storageMainDeletePkmVariant>>,
    TError,
    { params?: StorageMainDeletePkmVariantParams },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof storageMainDeletePkmVariant>>,
  TError,
  { params?: StorageMainDeletePkmVariantParams },
  TContext
> => {
  const mutationKey = ["storageMainDeletePkmVariant"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof storageMainDeletePkmVariant>>,
    { params?: StorageMainDeletePkmVariantParams }
  > = (props) => {
    const { params } = props ?? {};

    return storageMainDeletePkmVariant(params, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type StorageMainDeletePkmVariantMutationResult = NonNullable<
  Awaited<ReturnType<typeof storageMainDeletePkmVariant>>
>;

export type StorageMainDeletePkmVariantMutationError = ErrorType<unknown>;

export const useStorageMainDeletePkmVariant = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof storageMainDeletePkmVariant>>,
      TError,
      { params?: StorageMainDeletePkmVariantParams },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof storageMainDeletePkmVariant>>,
  TError,
  { params?: StorageMainDeletePkmVariantParams },
  TContext
> => {
  return useMutation(
    getStorageMainDeletePkmVariantMutationOptions(options),
    queryClient,
  );
};
export type storageGetBoxesResponse200TextPlain = {
  data: BoxDTO[];
  status: 200;
};

export type storageGetBoxesResponse200ApplicationJson = {
  data: BoxDTO[];
  status: 200;
};

export type storageGetBoxesResponse200TextJson = {
  data: BoxDTO[];
  status: 200;
};

export type storageGetBoxesResponseSuccess = (
  | storageGetBoxesResponse200TextPlain
  | storageGetBoxesResponse200ApplicationJson
  | storageGetBoxesResponse200TextJson
) & {
  headers: Headers;
};
export const getStorageGetBoxesUrl = (params?: StorageGetBoxesParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/storage/box?${stringifiedParams}`
    : `/api/storage/box`;
};

export const storageGetBoxes = async (
  params?: StorageGetBoxesParams,
  options?: RequestInit,
): Promise<storageGetBoxesResponseSuccess> => {
  return customInstance<storageGetBoxesResponseSuccess>(
    getStorageGetBoxesUrl(params),
    {
      ...options,
      method: "GET",
    },
  );
};

export const getStorageGetBoxesQueryKey = (params?: StorageGetBoxesParams) => {
  return [`/api/storage/box`, ...(params ? [params] : [])] as const;
};

export const getStorageGetBoxesQueryOptions = <
  TData = Awaited<ReturnType<typeof storageGetBoxes>>,
  TError = ErrorType<unknown>,
>(
  params?: StorageGetBoxesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof storageGetBoxes>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getStorageGetBoxesQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof storageGetBoxes>>> = ({
    signal,
  }) => storageGetBoxes(params, { signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof storageGetBoxes>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type StorageGetBoxesQueryResult = NonNullable<
  Awaited<ReturnType<typeof storageGetBoxes>>
>;
export type StorageGetBoxesQueryError = ErrorType<unknown>;

export function useStorageGetBoxes<
  TData = Awaited<ReturnType<typeof storageGetBoxes>>,
  TError = ErrorType<unknown>,
>(
  params: undefined | StorageGetBoxesParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof storageGetBoxes>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof storageGetBoxes>>,
          TError,
          Awaited<ReturnType<typeof storageGetBoxes>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useStorageGetBoxes<
  TData = Awaited<ReturnType<typeof storageGetBoxes>>,
  TError = ErrorType<unknown>,
>(
  params?: StorageGetBoxesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof storageGetBoxes>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof storageGetBoxes>>,
          TError,
          Awaited<ReturnType<typeof storageGetBoxes>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useStorageGetBoxes<
  TData = Awaited<ReturnType<typeof storageGetBoxes>>,
  TError = ErrorType<unknown>,
>(
  params?: StorageGetBoxesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof storageGetBoxes>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useStorageGetBoxes<
  TData = Awaited<ReturnType<typeof storageGetBoxes>>,
  TError = ErrorType<unknown>,
>(
  params?: StorageGetBoxesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof storageGetBoxes>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getStorageGetBoxesQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

export type storageGetSavePkmsResponse200TextPlain = {
  data: PkmSaveDTO[];
  status: 200;
};

export type storageGetSavePkmsResponse200ApplicationJson = {
  data: PkmSaveDTO[];
  status: 200;
};

export type storageGetSavePkmsResponse200TextJson = {
  data: PkmSaveDTO[];
  status: 200;
};

export type storageGetSavePkmsResponseSuccess = (
  | storageGetSavePkmsResponse200TextPlain
  | storageGetSavePkmsResponse200ApplicationJson
  | storageGetSavePkmsResponse200TextJson
) & {
  headers: Headers;
};
export const getStorageGetSavePkmsUrl = (saveId: number) => {
  return `/api/storage/save/${saveId}/pkm`;
};

export const storageGetSavePkms = async (
  saveId: number,
  options?: RequestInit,
): Promise<storageGetSavePkmsResponseSuccess> => {
  return customInstance<storageGetSavePkmsResponseSuccess>(
    getStorageGetSavePkmsUrl(saveId),
    {
      ...options,
      method: "GET",
    },
  );
};

export const getStorageGetSavePkmsQueryKey = (saveId: number) => {
  return [`/api/storage/save/${saveId}/pkm`] as const;
};

export const getStorageGetSavePkmsQueryOptions = <
  TData = Awaited<ReturnType<typeof storageGetSavePkms>>,
  TError = ErrorType<unknown>,
>(
  saveId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof storageGetSavePkms>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getStorageGetSavePkmsQueryKey(saveId);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof storageGetSavePkms>>
  > = ({ signal }) => storageGetSavePkms(saveId, { signal, ...requestOptions });

  return {
    queryKey,
    queryFn,
    enabled: !!saveId,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof storageGetSavePkms>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type StorageGetSavePkmsQueryResult = NonNullable<
  Awaited<ReturnType<typeof storageGetSavePkms>>
>;
export type StorageGetSavePkmsQueryError = ErrorType<unknown>;

export function useStorageGetSavePkms<
  TData = Awaited<ReturnType<typeof storageGetSavePkms>>,
  TError = ErrorType<unknown>,
>(
  saveId: number,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof storageGetSavePkms>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof storageGetSavePkms>>,
          TError,
          Awaited<ReturnType<typeof storageGetSavePkms>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useStorageGetSavePkms<
  TData = Awaited<ReturnType<typeof storageGetSavePkms>>,
  TError = ErrorType<unknown>,
>(
  saveId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof storageGetSavePkms>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof storageGetSavePkms>>,
          TError,
          Awaited<ReturnType<typeof storageGetSavePkms>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useStorageGetSavePkms<
  TData = Awaited<ReturnType<typeof storageGetSavePkms>>,
  TError = ErrorType<unknown>,
>(
  saveId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof storageGetSavePkms>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useStorageGetSavePkms<
  TData = Awaited<ReturnType<typeof storageGetSavePkms>>,
  TError = ErrorType<unknown>,
>(
  saveId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof storageGetSavePkms>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getStorageGetSavePkmsQueryOptions(saveId, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

export type storageSaveDeletePkmsResponse200TextPlain = {
  data: DataDTO;
  status: 200;
};

export type storageSaveDeletePkmsResponse200ApplicationJson = {
  data: DataDTO;
  status: 200;
};

export type storageSaveDeletePkmsResponse200TextJson = {
  data: DataDTO;
  status: 200;
};

export type storageSaveDeletePkmsResponseSuccess = (
  | storageSaveDeletePkmsResponse200TextPlain
  | storageSaveDeletePkmsResponse200ApplicationJson
  | storageSaveDeletePkmsResponse200TextJson
) & {
  headers: Headers;
};
export const getStorageSaveDeletePkmsUrl = (
  saveId: number,
  params?: StorageSaveDeletePkmsParams,
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    const explodeParameters = ["pkmIds"];

    if (Array.isArray(value) && explodeParameters.includes(key)) {
      value.forEach((v) => {
        normalizedParams.append(key, v === null ? "null" : v.toString());
      });
      return;
    }

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/storage/save/${saveId}/pkm?${stringifiedParams}`
    : `/api/storage/save/${saveId}/pkm`;
};

export const storageSaveDeletePkms = async (
  saveId: number,
  params?: StorageSaveDeletePkmsParams,
  options?: RequestInit,
): Promise<storageSaveDeletePkmsResponseSuccess> => {
  return customInstance<storageSaveDeletePkmsResponseSuccess>(
    getStorageSaveDeletePkmsUrl(saveId, params),
    {
      ...options,
      method: "DELETE",
    },
  );
};

export const getStorageSaveDeletePkmsMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof storageSaveDeletePkms>>,
    TError,
    { saveId: number; params?: StorageSaveDeletePkmsParams },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof storageSaveDeletePkms>>,
  TError,
  { saveId: number; params?: StorageSaveDeletePkmsParams },
  TContext
> => {
  const mutationKey = ["storageSaveDeletePkms"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof storageSaveDeletePkms>>,
    { saveId: number; params?: StorageSaveDeletePkmsParams }
  > = (props) => {
    const { saveId, params } = props ?? {};

    return storageSaveDeletePkms(saveId, params, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type StorageSaveDeletePkmsMutationResult = NonNullable<
  Awaited<ReturnType<typeof storageSaveDeletePkms>>
>;

export type StorageSaveDeletePkmsMutationError = ErrorType<unknown>;

export const useStorageSaveDeletePkms = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof storageSaveDeletePkms>>,
      TError,
      { saveId: number; params?: StorageSaveDeletePkmsParams },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof storageSaveDeletePkms>>,
  TError,
  { saveId: number; params?: StorageSaveDeletePkmsParams },
  TContext
> => {
  return useMutation(
    getStorageSaveDeletePkmsMutationOptions(options),
    queryClient,
  );
};
export type storageGetPkmsLegalityResponse200TextPlain = {
  data: StorageGetPkmsLegality200One;
  status: 200;
};

export type storageGetPkmsLegalityResponse200ApplicationJson = {
  data: StorageGetPkmsLegality200Two;
  status: 200;
};

export type storageGetPkmsLegalityResponse200TextJson = {
  data: StorageGetPkmsLegality200Three;
  status: 200;
};

export type storageGetPkmsLegalityResponseSuccess = (
  | storageGetPkmsLegalityResponse200TextPlain
  | storageGetPkmsLegalityResponse200ApplicationJson
  | storageGetPkmsLegalityResponse200TextJson
) & {
  headers: Headers;
};
export const getStorageGetPkmsLegalityUrl = (
  params?: StorageGetPkmsLegalityParams,
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    const explodeParameters = ["pkmIds"];

    if (Array.isArray(value) && explodeParameters.includes(key)) {
      value.forEach((v) => {
        normalizedParams.append(key, v === null ? "null" : v.toString());
      });
      return;
    }

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/storage/pkm/legality?${stringifiedParams}`
    : `/api/storage/pkm/legality`;
};

export const storageGetPkmsLegality = async (
  params?: StorageGetPkmsLegalityParams,
  options?: RequestInit,
): Promise<storageGetPkmsLegalityResponseSuccess> => {
  return customInstance<storageGetPkmsLegalityResponseSuccess>(
    getStorageGetPkmsLegalityUrl(params),
    {
      ...options,
      method: "GET",
    },
  );
};

export const getStorageGetPkmsLegalityQueryKey = (
  params?: StorageGetPkmsLegalityParams,
) => {
  return [`/api/storage/pkm/legality`, ...(params ? [params] : [])] as const;
};

export const getStorageGetPkmsLegalityQueryOptions = <
  TData = Awaited<ReturnType<typeof storageGetPkmsLegality>>,
  TError = ErrorType<unknown>,
>(
  params?: StorageGetPkmsLegalityParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof storageGetPkmsLegality>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getStorageGetPkmsLegalityQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof storageGetPkmsLegality>>
  > = ({ signal }) =>
    storageGetPkmsLegality(params, { signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof storageGetPkmsLegality>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type StorageGetPkmsLegalityQueryResult = NonNullable<
  Awaited<ReturnType<typeof storageGetPkmsLegality>>
>;
export type StorageGetPkmsLegalityQueryError = ErrorType<unknown>;

export function useStorageGetPkmsLegality<
  TData = Awaited<ReturnType<typeof storageGetPkmsLegality>>,
  TError = ErrorType<unknown>,
>(
  params: undefined | StorageGetPkmsLegalityParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof storageGetPkmsLegality>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof storageGetPkmsLegality>>,
          TError,
          Awaited<ReturnType<typeof storageGetPkmsLegality>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useStorageGetPkmsLegality<
  TData = Awaited<ReturnType<typeof storageGetPkmsLegality>>,
  TError = ErrorType<unknown>,
>(
  params?: StorageGetPkmsLegalityParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof storageGetPkmsLegality>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof storageGetPkmsLegality>>,
          TError,
          Awaited<ReturnType<typeof storageGetPkmsLegality>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useStorageGetPkmsLegality<
  TData = Awaited<ReturnType<typeof storageGetPkmsLegality>>,
  TError = ErrorType<unknown>,
>(
  params?: StorageGetPkmsLegalityParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof storageGetPkmsLegality>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useStorageGetPkmsLegality<
  TData = Awaited<ReturnType<typeof storageGetPkmsLegality>>,
  TError = ErrorType<unknown>,
>(
  params?: StorageGetPkmsLegalityParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof storageGetPkmsLegality>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getStorageGetPkmsLegalityQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

export type storageMovePkmResponse200TextPlain = {
  data: DataDTO;
  status: 200;
};

export type storageMovePkmResponse200ApplicationJson = {
  data: DataDTO;
  status: 200;
};

export type storageMovePkmResponse200TextJson = {
  data: DataDTO;
  status: 200;
};

export type storageMovePkmResponseSuccess = (
  | storageMovePkmResponse200TextPlain
  | storageMovePkmResponse200ApplicationJson
  | storageMovePkmResponse200TextJson
) & {
  headers: Headers;
};
export const getStorageMovePkmUrl = (params: StorageMovePkmParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    const explodeParameters = ["pkmIds", "targetBoxSlots"];

    if (Array.isArray(value) && explodeParameters.includes(key)) {
      value.forEach((v) => {
        normalizedParams.append(key, v === null ? "null" : v.toString());
      });
      return;
    }

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/storage/move/pkm?${stringifiedParams}`
    : `/api/storage/move/pkm`;
};

export const storageMovePkm = async (
  params: StorageMovePkmParams,
  options?: RequestInit,
): Promise<storageMovePkmResponseSuccess> => {
  return customInstance<storageMovePkmResponseSuccess>(
    getStorageMovePkmUrl(params),
    {
      ...options,
      method: "PUT",
    },
  );
};

export const getStorageMovePkmMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof storageMovePkm>>,
    TError,
    { params: StorageMovePkmParams },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof storageMovePkm>>,
  TError,
  { params: StorageMovePkmParams },
  TContext
> => {
  const mutationKey = ["storageMovePkm"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof storageMovePkm>>,
    { params: StorageMovePkmParams }
  > = (props) => {
    const { params } = props ?? {};

    return storageMovePkm(params, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type StorageMovePkmMutationResult = NonNullable<
  Awaited<ReturnType<typeof storageMovePkm>>
>;

export type StorageMovePkmMutationError = ErrorType<unknown>;

export const useStorageMovePkm = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof storageMovePkm>>,
      TError,
      { params: StorageMovePkmParams },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof storageMovePkm>>,
  TError,
  { params: StorageMovePkmParams },
  TContext
> => {
  return useMutation(getStorageMovePkmMutationOptions(options), queryClient);
};
export type storageMovePkmBankResponse200TextPlain = {
  data: DataDTO;
  status: 200;
};

export type storageMovePkmBankResponse200ApplicationJson = {
  data: DataDTO;
  status: 200;
};

export type storageMovePkmBankResponse200TextJson = {
  data: DataDTO;
  status: 200;
};

export type storageMovePkmBankResponseSuccess = (
  | storageMovePkmBankResponse200TextPlain
  | storageMovePkmBankResponse200ApplicationJson
  | storageMovePkmBankResponse200TextJson
) & {
  headers: Headers;
};
export const getStorageMovePkmBankUrl = (params?: StorageMovePkmBankParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    const explodeParameters = ["pkmIds"];

    if (Array.isArray(value) && explodeParameters.includes(key)) {
      value.forEach((v) => {
        normalizedParams.append(key, v === null ? "null" : v.toString());
      });
      return;
    }

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/storage/move/pkm/bank?${stringifiedParams}`
    : `/api/storage/move/pkm/bank`;
};

export const storageMovePkmBank = async (
  params?: StorageMovePkmBankParams,
  options?: RequestInit,
): Promise<storageMovePkmBankResponseSuccess> => {
  return customInstance<storageMovePkmBankResponseSuccess>(
    getStorageMovePkmBankUrl(params),
    {
      ...options,
      method: "PUT",
    },
  );
};

export const getStorageMovePkmBankMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof storageMovePkmBank>>,
    TError,
    { params?: StorageMovePkmBankParams },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof storageMovePkmBank>>,
  TError,
  { params?: StorageMovePkmBankParams },
  TContext
> => {
  const mutationKey = ["storageMovePkmBank"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof storageMovePkmBank>>,
    { params?: StorageMovePkmBankParams }
  > = (props) => {
    const { params } = props ?? {};

    return storageMovePkmBank(params, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type StorageMovePkmBankMutationResult = NonNullable<
  Awaited<ReturnType<typeof storageMovePkmBank>>
>;

export type StorageMovePkmBankMutationError = ErrorType<unknown>;

export const useStorageMovePkmBank = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof storageMovePkmBank>>,
      TError,
      { params?: StorageMovePkmBankParams },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof storageMovePkmBank>>,
  TError,
  { params?: StorageMovePkmBankParams },
  TContext
> => {
  return useMutation(
    getStorageMovePkmBankMutationOptions(options),
    queryClient,
  );
};
export type storageCreateMainBoxResponse200TextPlain = {
  data: DataDTO;
  status: 200;
};

export type storageCreateMainBoxResponse200ApplicationJson = {
  data: DataDTO;
  status: 200;
};

export type storageCreateMainBoxResponse200TextJson = {
  data: DataDTO;
  status: 200;
};

export type storageCreateMainBoxResponseSuccess = (
  | storageCreateMainBoxResponse200TextPlain
  | storageCreateMainBoxResponse200ApplicationJson
  | storageCreateMainBoxResponse200TextJson
) & {
  headers: Headers;
};
export const getStorageCreateMainBoxUrl = (
  params: StorageCreateMainBoxParams,
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/storage/main/box?${stringifiedParams}`
    : `/api/storage/main/box`;
};

export const storageCreateMainBox = async (
  params: StorageCreateMainBoxParams,
  options?: RequestInit,
): Promise<storageCreateMainBoxResponseSuccess> => {
  return customInstance<storageCreateMainBoxResponseSuccess>(
    getStorageCreateMainBoxUrl(params),
    {
      ...options,
      method: "POST",
    },
  );
};

export const getStorageCreateMainBoxMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof storageCreateMainBox>>,
    TError,
    { params: StorageCreateMainBoxParams },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof storageCreateMainBox>>,
  TError,
  { params: StorageCreateMainBoxParams },
  TContext
> => {
  const mutationKey = ["storageCreateMainBox"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof storageCreateMainBox>>,
    { params: StorageCreateMainBoxParams }
  > = (props) => {
    const { params } = props ?? {};

    return storageCreateMainBox(params, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type StorageCreateMainBoxMutationResult = NonNullable<
  Awaited<ReturnType<typeof storageCreateMainBox>>
>;

export type StorageCreateMainBoxMutationError = ErrorType<unknown>;

export const useStorageCreateMainBox = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof storageCreateMainBox>>,
      TError,
      { params: StorageCreateMainBoxParams },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof storageCreateMainBox>>,
  TError,
  { params: StorageCreateMainBoxParams },
  TContext
> => {
  return useMutation(
    getStorageCreateMainBoxMutationOptions(options),
    queryClient,
  );
};
export type storageUpdateMainBoxResponse200TextPlain = {
  data: DataDTO;
  status: 200;
};

export type storageUpdateMainBoxResponse200ApplicationJson = {
  data: DataDTO;
  status: 200;
};

export type storageUpdateMainBoxResponse200TextJson = {
  data: DataDTO;
  status: 200;
};

export type storageUpdateMainBoxResponseSuccess = (
  | storageUpdateMainBoxResponse200TextPlain
  | storageUpdateMainBoxResponse200ApplicationJson
  | storageUpdateMainBoxResponse200TextJson
) & {
  headers: Headers;
};
export const getStorageUpdateMainBoxUrl = (
  boxId: string,
  params: StorageUpdateMainBoxParams,
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/storage/main/box/${boxId}?${stringifiedParams}`
    : `/api/storage/main/box/${boxId}`;
};

export const storageUpdateMainBox = async (
  boxId: string,
  params: StorageUpdateMainBoxParams,
  options?: RequestInit,
): Promise<storageUpdateMainBoxResponseSuccess> => {
  return customInstance<storageUpdateMainBoxResponseSuccess>(
    getStorageUpdateMainBoxUrl(boxId, params),
    {
      ...options,
      method: "PUT",
    },
  );
};

export const getStorageUpdateMainBoxMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof storageUpdateMainBox>>,
    TError,
    { boxId: string; params: StorageUpdateMainBoxParams },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof storageUpdateMainBox>>,
  TError,
  { boxId: string; params: StorageUpdateMainBoxParams },
  TContext
> => {
  const mutationKey = ["storageUpdateMainBox"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof storageUpdateMainBox>>,
    { boxId: string; params: StorageUpdateMainBoxParams }
  > = (props) => {
    const { boxId, params } = props ?? {};

    return storageUpdateMainBox(boxId, params, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type StorageUpdateMainBoxMutationResult = NonNullable<
  Awaited<ReturnType<typeof storageUpdateMainBox>>
>;

export type StorageUpdateMainBoxMutationError = ErrorType<unknown>;

export const useStorageUpdateMainBox = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof storageUpdateMainBox>>,
      TError,
      { boxId: string; params: StorageUpdateMainBoxParams },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof storageUpdateMainBox>>,
  TError,
  { boxId: string; params: StorageUpdateMainBoxParams },
  TContext
> => {
  return useMutation(
    getStorageUpdateMainBoxMutationOptions(options),
    queryClient,
  );
};
export type storageDeleteMainBoxResponse200TextPlain = {
  data: DataDTO;
  status: 200;
};

export type storageDeleteMainBoxResponse200ApplicationJson = {
  data: DataDTO;
  status: 200;
};

export type storageDeleteMainBoxResponse200TextJson = {
  data: DataDTO;
  status: 200;
};

export type storageDeleteMainBoxResponseSuccess = (
  | storageDeleteMainBoxResponse200TextPlain
  | storageDeleteMainBoxResponse200ApplicationJson
  | storageDeleteMainBoxResponse200TextJson
) & {
  headers: Headers;
};
export const getStorageDeleteMainBoxUrl = (boxId: string) => {
  return `/api/storage/main/box/${boxId}`;
};

export const storageDeleteMainBox = async (
  boxId: string,
  options?: RequestInit,
): Promise<storageDeleteMainBoxResponseSuccess> => {
  return customInstance<storageDeleteMainBoxResponseSuccess>(
    getStorageDeleteMainBoxUrl(boxId),
    {
      ...options,
      method: "DELETE",
    },
  );
};

export const getStorageDeleteMainBoxMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof storageDeleteMainBox>>,
    TError,
    { boxId: string },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof storageDeleteMainBox>>,
  TError,
  { boxId: string },
  TContext
> => {
  const mutationKey = ["storageDeleteMainBox"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof storageDeleteMainBox>>,
    { boxId: string }
  > = (props) => {
    const { boxId } = props ?? {};

    return storageDeleteMainBox(boxId, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type StorageDeleteMainBoxMutationResult = NonNullable<
  Awaited<ReturnType<typeof storageDeleteMainBox>>
>;

export type StorageDeleteMainBoxMutationError = ErrorType<unknown>;

export const useStorageDeleteMainBox = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof storageDeleteMainBox>>,
      TError,
      { boxId: string },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof storageDeleteMainBox>>,
  TError,
  { boxId: string },
  TContext
> => {
  return useMutation(
    getStorageDeleteMainBoxMutationOptions(options),
    queryClient,
  );
};
export type storageUpdateMainBankResponse200TextPlain = {
  data: DataDTO;
  status: 200;
};

export type storageUpdateMainBankResponse200ApplicationJson = {
  data: DataDTO;
  status: 200;
};

export type storageUpdateMainBankResponse200TextJson = {
  data: DataDTO;
  status: 200;
};

export type storageUpdateMainBankResponseSuccess = (
  | storageUpdateMainBankResponse200TextPlain
  | storageUpdateMainBankResponse200ApplicationJson
  | storageUpdateMainBankResponse200TextJson
) & {
  headers: Headers;
};
export const getStorageUpdateMainBankUrl = (
  bankId: string,
  params: StorageUpdateMainBankParams,
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/storage/main/bank/${bankId}?${stringifiedParams}`
    : `/api/storage/main/bank/${bankId}`;
};

export const storageUpdateMainBank = async (
  bankId: string,
  bankView: BankView,
  params: StorageUpdateMainBankParams,
  options?: RequestInit,
): Promise<storageUpdateMainBankResponseSuccess> => {
  return customInstance<storageUpdateMainBankResponseSuccess>(
    getStorageUpdateMainBankUrl(bankId, params),
    {
      ...options,
      method: "PUT",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(bankView),
    },
  );
};

export const getStorageUpdateMainBankMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof storageUpdateMainBank>>,
    TError,
    { bankId: string; data: BankView; params: StorageUpdateMainBankParams },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof storageUpdateMainBank>>,
  TError,
  { bankId: string; data: BankView; params: StorageUpdateMainBankParams },
  TContext
> => {
  const mutationKey = ["storageUpdateMainBank"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof storageUpdateMainBank>>,
    { bankId: string; data: BankView; params: StorageUpdateMainBankParams }
  > = (props) => {
    const { bankId, data, params } = props ?? {};

    return storageUpdateMainBank(bankId, data, params, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type StorageUpdateMainBankMutationResult = NonNullable<
  Awaited<ReturnType<typeof storageUpdateMainBank>>
>;
export type StorageUpdateMainBankMutationBody = BankView;
export type StorageUpdateMainBankMutationError = ErrorType<unknown>;

export const useStorageUpdateMainBank = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof storageUpdateMainBank>>,
      TError,
      { bankId: string; data: BankView; params: StorageUpdateMainBankParams },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof storageUpdateMainBank>>,
  TError,
  { bankId: string; data: BankView; params: StorageUpdateMainBankParams },
  TContext
> => {
  return useMutation(
    getStorageUpdateMainBankMutationOptions(options),
    queryClient,
  );
};
export type storageDeleteMainBankResponse200TextPlain = {
  data: DataDTO;
  status: 200;
};

export type storageDeleteMainBankResponse200ApplicationJson = {
  data: DataDTO;
  status: 200;
};

export type storageDeleteMainBankResponse200TextJson = {
  data: DataDTO;
  status: 200;
};

export type storageDeleteMainBankResponseSuccess = (
  | storageDeleteMainBankResponse200TextPlain
  | storageDeleteMainBankResponse200ApplicationJson
  | storageDeleteMainBankResponse200TextJson
) & {
  headers: Headers;
};
export const getStorageDeleteMainBankUrl = (bankId: string) => {
  return `/api/storage/main/bank/${bankId}`;
};

export const storageDeleteMainBank = async (
  bankId: string,
  options?: RequestInit,
): Promise<storageDeleteMainBankResponseSuccess> => {
  return customInstance<storageDeleteMainBankResponseSuccess>(
    getStorageDeleteMainBankUrl(bankId),
    {
      ...options,
      method: "DELETE",
    },
  );
};

export const getStorageDeleteMainBankMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof storageDeleteMainBank>>,
    TError,
    { bankId: string },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof storageDeleteMainBank>>,
  TError,
  { bankId: string },
  TContext
> => {
  const mutationKey = ["storageDeleteMainBank"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof storageDeleteMainBank>>,
    { bankId: string }
  > = (props) => {
    const { bankId } = props ?? {};

    return storageDeleteMainBank(bankId, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type StorageDeleteMainBankMutationResult = NonNullable<
  Awaited<ReturnType<typeof storageDeleteMainBank>>
>;

export type StorageDeleteMainBankMutationError = ErrorType<unknown>;

export const useStorageDeleteMainBank = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof storageDeleteMainBank>>,
      TError,
      { bankId: string },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof storageDeleteMainBank>>,
  TError,
  { bankId: string },
  TContext
> => {
  return useMutation(
    getStorageDeleteMainBankMutationOptions(options),
    queryClient,
  );
};
export type storageMainPkmDetachSaveResponse200TextPlain = {
  data: DataDTO;
  status: 200;
};

export type storageMainPkmDetachSaveResponse200ApplicationJson = {
  data: DataDTO;
  status: 200;
};

export type storageMainPkmDetachSaveResponse200TextJson = {
  data: DataDTO;
  status: 200;
};

export type storageMainPkmDetachSaveResponseSuccess = (
  | storageMainPkmDetachSaveResponse200TextPlain
  | storageMainPkmDetachSaveResponse200ApplicationJson
  | storageMainPkmDetachSaveResponse200TextJson
) & {
  headers: Headers;
};
export const getStorageMainPkmDetachSaveUrl = (
  params?: StorageMainPkmDetachSaveParams,
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    const explodeParameters = ["pkmVariantIds"];

    if (Array.isArray(value) && explodeParameters.includes(key)) {
      value.forEach((v) => {
        normalizedParams.append(key, v === null ? "null" : v.toString());
      });
      return;
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/storage/main/pkm/detach-save?${stringifiedParams}`
    : `/api/storage/main/pkm/detach-save`;
};

export const storageMainPkmDetachSave = async (
  params?: StorageMainPkmDetachSaveParams,
  options?: RequestInit,
): Promise<storageMainPkmDetachSaveResponseSuccess> => {
  return customInstance<storageMainPkmDetachSaveResponseSuccess>(
    getStorageMainPkmDetachSaveUrl(params),
    {
      ...options,
      method: "PUT",
    },
  );
};

export const getStorageMainPkmDetachSaveMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof storageMainPkmDetachSave>>,
    TError,
    { params?: StorageMainPkmDetachSaveParams },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof storageMainPkmDetachSave>>,
  TError,
  { params?: StorageMainPkmDetachSaveParams },
  TContext
> => {
  const mutationKey = ["storageMainPkmDetachSave"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof storageMainPkmDetachSave>>,
    { params?: StorageMainPkmDetachSaveParams }
  > = (props) => {
    const { params } = props ?? {};

    return storageMainPkmDetachSave(params, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type StorageMainPkmDetachSaveMutationResult = NonNullable<
  Awaited<ReturnType<typeof storageMainPkmDetachSave>>
>;

export type StorageMainPkmDetachSaveMutationError = ErrorType<unknown>;

export const useStorageMainPkmDetachSave = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof storageMainPkmDetachSave>>,
      TError,
      { params?: StorageMainPkmDetachSaveParams },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof storageMainPkmDetachSave>>,
  TError,
  { params?: StorageMainPkmDetachSaveParams },
  TContext
> => {
  return useMutation(
    getStorageMainPkmDetachSaveMutationOptions(options),
    queryClient,
  );
};
export type storageMainEditPkmVariantResponse200TextPlain = {
  data: DataDTO;
  status: 200;
};

export type storageMainEditPkmVariantResponse200ApplicationJson = {
  data: DataDTO;
  status: 200;
};

export type storageMainEditPkmVariantResponse200TextJson = {
  data: DataDTO;
  status: 200;
};

export type storageMainEditPkmVariantResponseSuccess = (
  | storageMainEditPkmVariantResponse200TextPlain
  | storageMainEditPkmVariantResponse200ApplicationJson
  | storageMainEditPkmVariantResponse200TextJson
) & {
  headers: Headers;
};
export const getStorageMainEditPkmVariantUrl = (pkmVariantId: string) => {
  return `/api/storage/main/pkm-version/${pkmVariantId}`;
};

export const storageMainEditPkmVariant = async (
  pkmVariantId: string,
  editPkmVariantPayload: EditPkmVariantPayload,
  options?: RequestInit,
): Promise<storageMainEditPkmVariantResponseSuccess> => {
  return customInstance<storageMainEditPkmVariantResponseSuccess>(
    getStorageMainEditPkmVariantUrl(pkmVariantId),
    {
      ...options,
      method: "PUT",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(editPkmVariantPayload),
    },
  );
};

export const getStorageMainEditPkmVariantMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof storageMainEditPkmVariant>>,
    TError,
    { pkmVariantId: string; data: EditPkmVariantPayload },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof storageMainEditPkmVariant>>,
  TError,
  { pkmVariantId: string; data: EditPkmVariantPayload },
  TContext
> => {
  const mutationKey = ["storageMainEditPkmVariant"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof storageMainEditPkmVariant>>,
    { pkmVariantId: string; data: EditPkmVariantPayload }
  > = (props) => {
    const { pkmVariantId, data } = props ?? {};

    return storageMainEditPkmVariant(pkmVariantId, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type StorageMainEditPkmVariantMutationResult = NonNullable<
  Awaited<ReturnType<typeof storageMainEditPkmVariant>>
>;
export type StorageMainEditPkmVariantMutationBody = EditPkmVariantPayload;
export type StorageMainEditPkmVariantMutationError = ErrorType<unknown>;

export const useStorageMainEditPkmVariant = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof storageMainEditPkmVariant>>,
      TError,
      { pkmVariantId: string; data: EditPkmVariantPayload },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof storageMainEditPkmVariant>>,
  TError,
  { pkmVariantId: string; data: EditPkmVariantPayload },
  TContext
> => {
  return useMutation(
    getStorageMainEditPkmVariantMutationOptions(options),
    queryClient,
  );
};
export type storageSaveEditPkmResponse200TextPlain = {
  data: DataDTO;
  status: 200;
};

export type storageSaveEditPkmResponse200ApplicationJson = {
  data: DataDTO;
  status: 200;
};

export type storageSaveEditPkmResponse200TextJson = {
  data: DataDTO;
  status: 200;
};

export type storageSaveEditPkmResponseSuccess = (
  | storageSaveEditPkmResponse200TextPlain
  | storageSaveEditPkmResponse200ApplicationJson
  | storageSaveEditPkmResponse200TextJson
) & {
  headers: Headers;
};
export const getStorageSaveEditPkmUrl = (saveId: number, pkmId: string) => {
  return `/api/storage/save/${saveId}/pkm/${pkmId}`;
};

export const storageSaveEditPkm = async (
  saveId: number,
  pkmId: string,
  editPkmVariantPayload: EditPkmVariantPayload,
  options?: RequestInit,
): Promise<storageSaveEditPkmResponseSuccess> => {
  return customInstance<storageSaveEditPkmResponseSuccess>(
    getStorageSaveEditPkmUrl(saveId, pkmId),
    {
      ...options,
      method: "PUT",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(editPkmVariantPayload),
    },
  );
};

export const getStorageSaveEditPkmMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof storageSaveEditPkm>>,
    TError,
    { saveId: number; pkmId: string; data: EditPkmVariantPayload },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof storageSaveEditPkm>>,
  TError,
  { saveId: number; pkmId: string; data: EditPkmVariantPayload },
  TContext
> => {
  const mutationKey = ["storageSaveEditPkm"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof storageSaveEditPkm>>,
    { saveId: number; pkmId: string; data: EditPkmVariantPayload }
  > = (props) => {
    const { saveId, pkmId, data } = props ?? {};

    return storageSaveEditPkm(saveId, pkmId, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type StorageSaveEditPkmMutationResult = NonNullable<
  Awaited<ReturnType<typeof storageSaveEditPkm>>
>;
export type StorageSaveEditPkmMutationBody = EditPkmVariantPayload;
export type StorageSaveEditPkmMutationError = ErrorType<unknown>;

export const useStorageSaveEditPkm = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof storageSaveEditPkm>>,
      TError,
      { saveId: number; pkmId: string; data: EditPkmVariantPayload },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof storageSaveEditPkm>>,
  TError,
  { saveId: number; pkmId: string; data: EditPkmVariantPayload },
  TContext
> => {
  return useMutation(
    getStorageSaveEditPkmMutationOptions(options),
    queryClient,
  );
};
export type storageEvolvePkmsResponse200TextPlain = {
  data: DataDTO;
  status: 200;
};

export type storageEvolvePkmsResponse200ApplicationJson = {
  data: DataDTO;
  status: 200;
};

export type storageEvolvePkmsResponse200TextJson = {
  data: DataDTO;
  status: 200;
};

export type storageEvolvePkmsResponseSuccess = (
  | storageEvolvePkmsResponse200TextPlain
  | storageEvolvePkmsResponse200ApplicationJson
  | storageEvolvePkmsResponse200TextJson
) & {
  headers: Headers;
};
export const getStorageEvolvePkmsUrl = (params?: StorageEvolvePkmsParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    const explodeParameters = ["ids"];

    if (Array.isArray(value) && explodeParameters.includes(key)) {
      value.forEach((v) => {
        normalizedParams.append(key, v === null ? "null" : v.toString());
      });
      return;
    }

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/storage/pkm/evolve?${stringifiedParams}`
    : `/api/storage/pkm/evolve`;
};

export const storageEvolvePkms = async (
  params?: StorageEvolvePkmsParams,
  options?: RequestInit,
): Promise<storageEvolvePkmsResponseSuccess> => {
  return customInstance<storageEvolvePkmsResponseSuccess>(
    getStorageEvolvePkmsUrl(params),
    {
      ...options,
      method: "PUT",
    },
  );
};

export const getStorageEvolvePkmsMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof storageEvolvePkms>>,
    TError,
    { params?: StorageEvolvePkmsParams },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof storageEvolvePkms>>,
  TError,
  { params?: StorageEvolvePkmsParams },
  TContext
> => {
  const mutationKey = ["storageEvolvePkms"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof storageEvolvePkms>>,
    { params?: StorageEvolvePkmsParams }
  > = (props) => {
    const { params } = props ?? {};

    return storageEvolvePkms(params, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type StorageEvolvePkmsMutationResult = NonNullable<
  Awaited<ReturnType<typeof storageEvolvePkms>>
>;

export type StorageEvolvePkmsMutationError = ErrorType<unknown>;

export const useStorageEvolvePkms = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof storageEvolvePkms>>,
      TError,
      { params?: StorageEvolvePkmsParams },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof storageEvolvePkms>>,
  TError,
  { params?: StorageEvolvePkmsParams },
  TContext
> => {
  return useMutation(getStorageEvolvePkmsMutationOptions(options), queryClient);
};
export type storageSortPkmsResponse200TextPlain = {
  data: DataDTO;
  status: 200;
};

export type storageSortPkmsResponse200ApplicationJson = {
  data: DataDTO;
  status: 200;
};

export type storageSortPkmsResponse200TextJson = {
  data: DataDTO;
  status: 200;
};

export type storageSortPkmsResponseSuccess = (
  | storageSortPkmsResponse200TextPlain
  | storageSortPkmsResponse200ApplicationJson
  | storageSortPkmsResponse200TextJson
) & {
  headers: Headers;
};
export const getStorageSortPkmsUrl = (params: StorageSortPkmsParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/storage/pkm/sort?${stringifiedParams}`
    : `/api/storage/pkm/sort`;
};

export const storageSortPkms = async (
  params: StorageSortPkmsParams,
  options?: RequestInit,
): Promise<storageSortPkmsResponseSuccess> => {
  return customInstance<storageSortPkmsResponseSuccess>(
    getStorageSortPkmsUrl(params),
    {
      ...options,
      method: "PUT",
    },
  );
};

export const getStorageSortPkmsMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof storageSortPkms>>,
    TError,
    { params: StorageSortPkmsParams },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof storageSortPkms>>,
  TError,
  { params: StorageSortPkmsParams },
  TContext
> => {
  const mutationKey = ["storageSortPkms"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof storageSortPkms>>,
    { params: StorageSortPkmsParams }
  > = (props) => {
    const { params } = props ?? {};

    return storageSortPkms(params, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type StorageSortPkmsMutationResult = NonNullable<
  Awaited<ReturnType<typeof storageSortPkms>>
>;

export type StorageSortPkmsMutationError = ErrorType<unknown>;

export const useStorageSortPkms = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof storageSortPkms>>,
      TError,
      { params: StorageSortPkmsParams },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof storageSortPkms>>,
  TError,
  { params: StorageSortPkmsParams },
  TContext
> => {
  return useMutation(getStorageSortPkmsMutationOptions(options), queryClient);
};
export type storageDexSyncResponse200TextPlain = {
  data: DataDTO;
  status: 200;
};

export type storageDexSyncResponse200ApplicationJson = {
  data: DataDTO;
  status: 200;
};

export type storageDexSyncResponse200TextJson = {
  data: DataDTO;
  status: 200;
};

export type storageDexSyncResponseSuccess = (
  | storageDexSyncResponse200TextPlain
  | storageDexSyncResponse200ApplicationJson
  | storageDexSyncResponse200TextJson
) & {
  headers: Headers;
};
export const getStorageDexSyncUrl = (params?: StorageDexSyncParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    const explodeParameters = ["saveIds"];

    if (Array.isArray(value) && explodeParameters.includes(key)) {
      value.forEach((v) => {
        normalizedParams.append(key, v === null ? "null" : v.toString());
      });
      return;
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/storage/dex/sync?${stringifiedParams}`
    : `/api/storage/dex/sync`;
};

export const storageDexSync = async (
  params?: StorageDexSyncParams,
  options?: RequestInit,
): Promise<storageDexSyncResponseSuccess> => {
  return customInstance<storageDexSyncResponseSuccess>(
    getStorageDexSyncUrl(params),
    {
      ...options,
      method: "PUT",
    },
  );
};

export const getStorageDexSyncMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof storageDexSync>>,
    TError,
    { params?: StorageDexSyncParams },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof storageDexSync>>,
  TError,
  { params?: StorageDexSyncParams },
  TContext
> => {
  const mutationKey = ["storageDexSync"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof storageDexSync>>,
    { params?: StorageDexSyncParams }
  > = (props) => {
    const { params } = props ?? {};

    return storageDexSync(params, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type StorageDexSyncMutationResult = NonNullable<
  Awaited<ReturnType<typeof storageDexSync>>
>;

export type StorageDexSyncMutationError = ErrorType<unknown>;

export const useStorageDexSync = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof storageDexSync>>,
      TError,
      { params?: StorageDexSyncParams },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof storageDexSync>>,
  TError,
  { params?: StorageDexSyncParams },
  TContext
> => {
  return useMutation(getStorageDexSyncMutationOptions(options), queryClient);
};
export type storageGetPkmAvailableMovesResponse200TextPlain = {
  data: MoveItem[];
  status: 200;
};

export type storageGetPkmAvailableMovesResponse200ApplicationJson = {
  data: MoveItem[];
  status: 200;
};

export type storageGetPkmAvailableMovesResponse200TextJson = {
  data: MoveItem[];
  status: 200;
};

export type storageGetPkmAvailableMovesResponseSuccess = (
  | storageGetPkmAvailableMovesResponse200TextPlain
  | storageGetPkmAvailableMovesResponse200ApplicationJson
  | storageGetPkmAvailableMovesResponse200TextJson
) & {
  headers: Headers;
};
export const getStorageGetPkmAvailableMovesUrl = (
  params?: StorageGetPkmAvailableMovesParams,
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/storage/pkm/available-moves?${stringifiedParams}`
    : `/api/storage/pkm/available-moves`;
};

export const storageGetPkmAvailableMoves = async (
  params?: StorageGetPkmAvailableMovesParams,
  options?: RequestInit,
): Promise<storageGetPkmAvailableMovesResponseSuccess> => {
  return customInstance<storageGetPkmAvailableMovesResponseSuccess>(
    getStorageGetPkmAvailableMovesUrl(params),
    {
      ...options,
      method: "GET",
    },
  );
};

export const getStorageGetPkmAvailableMovesQueryKey = (
  params?: StorageGetPkmAvailableMovesParams,
) => {
  return [
    `/api/storage/pkm/available-moves`,
    ...(params ? [params] : []),
  ] as const;
};

export const getStorageGetPkmAvailableMovesQueryOptions = <
  TData = Awaited<ReturnType<typeof storageGetPkmAvailableMoves>>,
  TError = ErrorType<unknown>,
>(
  params?: StorageGetPkmAvailableMovesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof storageGetPkmAvailableMoves>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getStorageGetPkmAvailableMovesQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof storageGetPkmAvailableMoves>>
  > = ({ signal }) =>
    storageGetPkmAvailableMoves(params, { signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof storageGetPkmAvailableMoves>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type StorageGetPkmAvailableMovesQueryResult = NonNullable<
  Awaited<ReturnType<typeof storageGetPkmAvailableMoves>>
>;
export type StorageGetPkmAvailableMovesQueryError = ErrorType<unknown>;

export function useStorageGetPkmAvailableMoves<
  TData = Awaited<ReturnType<typeof storageGetPkmAvailableMoves>>,
  TError = ErrorType<unknown>,
>(
  params: undefined | StorageGetPkmAvailableMovesParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof storageGetPkmAvailableMoves>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof storageGetPkmAvailableMoves>>,
          TError,
          Awaited<ReturnType<typeof storageGetPkmAvailableMoves>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useStorageGetPkmAvailableMoves<
  TData = Awaited<ReturnType<typeof storageGetPkmAvailableMoves>>,
  TError = ErrorType<unknown>,
>(
  params?: StorageGetPkmAvailableMovesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof storageGetPkmAvailableMoves>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof storageGetPkmAvailableMoves>>,
          TError,
          Awaited<ReturnType<typeof storageGetPkmAvailableMoves>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useStorageGetPkmAvailableMoves<
  TData = Awaited<ReturnType<typeof storageGetPkmAvailableMoves>>,
  TError = ErrorType<unknown>,
>(
  params?: StorageGetPkmAvailableMovesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof storageGetPkmAvailableMoves>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useStorageGetPkmAvailableMoves<
  TData = Awaited<ReturnType<typeof storageGetPkmAvailableMoves>>,
  TError = ErrorType<unknown>,
>(
  params?: StorageGetPkmAvailableMovesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof storageGetPkmAvailableMoves>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getStorageGetPkmAvailableMovesQueryOptions(
    params,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

export type storageGetActionsResponse200TextPlain = {
  data: DataActionPayload[];
  status: 200;
};

export type storageGetActionsResponse200ApplicationJson = {
  data: DataActionPayload[];
  status: 200;
};

export type storageGetActionsResponse200TextJson = {
  data: DataActionPayload[];
  status: 200;
};

export type storageGetActionsResponseSuccess = (
  | storageGetActionsResponse200TextPlain
  | storageGetActionsResponse200ApplicationJson
  | storageGetActionsResponse200TextJson
) & {
  headers: Headers;
};
export const getStorageGetActionsUrl = () => {
  return `/api/storage/action`;
};

export const storageGetActions = async (
  options?: RequestInit,
): Promise<storageGetActionsResponseSuccess> => {
  return customInstance<storageGetActionsResponseSuccess>(
    getStorageGetActionsUrl(),
    {
      ...options,
      method: "GET",
    },
  );
};

export const getStorageGetActionsQueryKey = () => {
  return [`/api/storage/action`] as const;
};

export const getStorageGetActionsQueryOptions = <
  TData = Awaited<ReturnType<typeof storageGetActions>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof storageGetActions>>,
      TError,
      TData
    >
  >;
  request?: SecondParameter<typeof customInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getStorageGetActionsQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof storageGetActions>>
  > = ({ signal }) => storageGetActions({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof storageGetActions>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type StorageGetActionsQueryResult = NonNullable<
  Awaited<ReturnType<typeof storageGetActions>>
>;
export type StorageGetActionsQueryError = ErrorType<unknown>;

export function useStorageGetActions<
  TData = Awaited<ReturnType<typeof storageGetActions>>,
  TError = ErrorType<unknown>,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof storageGetActions>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof storageGetActions>>,
          TError,
          Awaited<ReturnType<typeof storageGetActions>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useStorageGetActions<
  TData = Awaited<ReturnType<typeof storageGetActions>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof storageGetActions>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof storageGetActions>>,
          TError,
          Awaited<ReturnType<typeof storageGetActions>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useStorageGetActions<
  TData = Awaited<ReturnType<typeof storageGetActions>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof storageGetActions>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useStorageGetActions<
  TData = Awaited<ReturnType<typeof storageGetActions>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof storageGetActions>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getStorageGetActionsQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

export type storageDeleteActionsResponse200TextPlain = {
  data: DataDTO;
  status: 200;
};

export type storageDeleteActionsResponse200ApplicationJson = {
  data: DataDTO;
  status: 200;
};

export type storageDeleteActionsResponse200TextJson = {
  data: DataDTO;
  status: 200;
};

export type storageDeleteActionsResponseSuccess = (
  | storageDeleteActionsResponse200TextPlain
  | storageDeleteActionsResponse200ApplicationJson
  | storageDeleteActionsResponse200TextJson
) & {
  headers: Headers;
};
export const getStorageDeleteActionsUrl = (
  params: StorageDeleteActionsParams,
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/storage/action?${stringifiedParams}`
    : `/api/storage/action`;
};

export const storageDeleteActions = async (
  params: StorageDeleteActionsParams,
  options?: RequestInit,
): Promise<storageDeleteActionsResponseSuccess> => {
  return customInstance<storageDeleteActionsResponseSuccess>(
    getStorageDeleteActionsUrl(params),
    {
      ...options,
      method: "DELETE",
    },
  );
};

export const getStorageDeleteActionsMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof storageDeleteActions>>,
    TError,
    { params: StorageDeleteActionsParams },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof storageDeleteActions>>,
  TError,
  { params: StorageDeleteActionsParams },
  TContext
> => {
  const mutationKey = ["storageDeleteActions"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof storageDeleteActions>>,
    { params: StorageDeleteActionsParams }
  > = (props) => {
    const { params } = props ?? {};

    return storageDeleteActions(params, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type StorageDeleteActionsMutationResult = NonNullable<
  Awaited<ReturnType<typeof storageDeleteActions>>
>;

export type StorageDeleteActionsMutationError = ErrorType<unknown>;

export const useStorageDeleteActions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof storageDeleteActions>>,
      TError,
      { params: StorageDeleteActionsParams },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof storageDeleteActions>>,
  TError,
  { params: StorageDeleteActionsParams },
  TContext
> => {
  return useMutation(
    getStorageDeleteActionsMutationOptions(options),
    queryClient,
  );
};
export type storageSaveResponse200TextPlain = {
  data: DataDTO;
  status: 200;
};

export type storageSaveResponse200ApplicationJson = {
  data: DataDTO;
  status: 200;
};

export type storageSaveResponse200TextJson = {
  data: DataDTO;
  status: 200;
};

export type storageSaveResponseSuccess = (
  | storageSaveResponse200TextPlain
  | storageSaveResponse200ApplicationJson
  | storageSaveResponse200TextJson
) & {
  headers: Headers;
};
export const getStorageSaveUrl = () => {
  return `/api/storage/action/save`;
};

export const storageSave = async (
  options?: RequestInit,
): Promise<storageSaveResponseSuccess> => {
  return customInstance<storageSaveResponseSuccess>(getStorageSaveUrl(), {
    ...options,
    method: "POST",
  });
};

export const getStorageSaveMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof storageSave>>,
    TError,
    void,
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof storageSave>>,
  TError,
  void,
  TContext
> => {
  const mutationKey = ["storageSave"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof storageSave>>,
    void
  > = () => {
    return storageSave(requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type StorageSaveMutationResult = NonNullable<
  Awaited<ReturnType<typeof storageSave>>
>;

export type StorageSaveMutationError = ErrorType<unknown>;

export const useStorageSave = <TError = ErrorType<unknown>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof storageSave>>,
      TError,
      void,
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof storageSave>>,
  TError,
  void,
  TContext
> => {
  return useMutation(getStorageSaveMutationOptions(options), queryClient);
};
