/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * PKVault API
 * OpenAPI spec version: 1.0.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  BackupDTO,
  BackupDeleteParams,
  BackupEditParams,
  BackupRestoreParams,
  DataDTO,
} from "../model";

import { customInstance } from "../../mutator/custom-instance";
import type { ErrorType } from "../../mutator/custom-instance";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export type backupGetAllResponse200TextPlain = {
  data: BackupDTO[];
  status: 200;
};

export type backupGetAllResponse200ApplicationJson = {
  data: BackupDTO[];
  status: 200;
};

export type backupGetAllResponse200TextJson = {
  data: BackupDTO[];
  status: 200;
};

export type backupGetAllResponseSuccess = (
  | backupGetAllResponse200TextPlain
  | backupGetAllResponse200ApplicationJson
  | backupGetAllResponse200TextJson
) & {
  headers: Headers;
};
export const getBackupGetAllUrl = () => {
  return `/api/backup`;
};

export const backupGetAll = async (
  options?: RequestInit,
): Promise<backupGetAllResponseSuccess> => {
  return customInstance<backupGetAllResponseSuccess>(getBackupGetAllUrl(), {
    ...options,
    method: "GET",
  });
};

export const getBackupGetAllQueryKey = () => {
  return [`/api/backup`] as const;
};

export const getBackupGetAllQueryOptions = <
  TData = Awaited<ReturnType<typeof backupGetAll>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof backupGetAll>>, TError, TData>
  >;
  request?: SecondParameter<typeof customInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getBackupGetAllQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof backupGetAll>>> = ({
    signal,
  }) => backupGetAll({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof backupGetAll>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type BackupGetAllQueryResult = NonNullable<
  Awaited<ReturnType<typeof backupGetAll>>
>;
export type BackupGetAllQueryError = ErrorType<unknown>;

export function useBackupGetAll<
  TData = Awaited<ReturnType<typeof backupGetAll>>,
  TError = ErrorType<unknown>,
>(
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof backupGetAll>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof backupGetAll>>,
          TError,
          Awaited<ReturnType<typeof backupGetAll>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useBackupGetAll<
  TData = Awaited<ReturnType<typeof backupGetAll>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof backupGetAll>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof backupGetAll>>,
          TError,
          Awaited<ReturnType<typeof backupGetAll>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useBackupGetAll<
  TData = Awaited<ReturnType<typeof backupGetAll>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof backupGetAll>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useBackupGetAll<
  TData = Awaited<ReturnType<typeof backupGetAll>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof backupGetAll>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getBackupGetAllQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

export type backupEditResponse200TextPlain = {
  data: DataDTO;
  status: 200;
};

export type backupEditResponse200ApplicationJson = {
  data: DataDTO;
  status: 200;
};

export type backupEditResponse200TextJson = {
  data: DataDTO;
  status: 200;
};

export type backupEditResponseSuccess = (
  | backupEditResponse200TextPlain
  | backupEditResponse200ApplicationJson
  | backupEditResponse200TextJson
) & {
  headers: Headers;
};
export const getBackupEditUrl = (params: BackupEditParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/backup?${stringifiedParams}`
    : `/api/backup`;
};

export const backupEdit = async (
  params: BackupEditParams,
  options?: RequestInit,
): Promise<backupEditResponseSuccess> => {
  return customInstance<backupEditResponseSuccess>(getBackupEditUrl(params), {
    ...options,
    method: "PUT",
  });
};

export const getBackupEditMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof backupEdit>>,
    TError,
    { params: BackupEditParams },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof backupEdit>>,
  TError,
  { params: BackupEditParams },
  TContext
> => {
  const mutationKey = ["backupEdit"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof backupEdit>>,
    { params: BackupEditParams }
  > = (props) => {
    const { params } = props ?? {};

    return backupEdit(params, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type BackupEditMutationResult = NonNullable<
  Awaited<ReturnType<typeof backupEdit>>
>;

export type BackupEditMutationError = ErrorType<unknown>;

export const useBackupEdit = <TError = ErrorType<unknown>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof backupEdit>>,
      TError,
      { params: BackupEditParams },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof backupEdit>>,
  TError,
  { params: BackupEditParams },
  TContext
> => {
  return useMutation(getBackupEditMutationOptions(options), queryClient);
};
export type backupDeleteResponse200TextPlain = {
  data: DataDTO;
  status: 200;
};

export type backupDeleteResponse200ApplicationJson = {
  data: DataDTO;
  status: 200;
};

export type backupDeleteResponse200TextJson = {
  data: DataDTO;
  status: 200;
};

export type backupDeleteResponseSuccess = (
  | backupDeleteResponse200TextPlain
  | backupDeleteResponse200ApplicationJson
  | backupDeleteResponse200TextJson
) & {
  headers: Headers;
};
export const getBackupDeleteUrl = (params: BackupDeleteParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/backup?${stringifiedParams}`
    : `/api/backup`;
};

export const backupDelete = async (
  params: BackupDeleteParams,
  options?: RequestInit,
): Promise<backupDeleteResponseSuccess> => {
  return customInstance<backupDeleteResponseSuccess>(
    getBackupDeleteUrl(params),
    {
      ...options,
      method: "DELETE",
    },
  );
};

export const getBackupDeleteMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof backupDelete>>,
    TError,
    { params: BackupDeleteParams },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof backupDelete>>,
  TError,
  { params: BackupDeleteParams },
  TContext
> => {
  const mutationKey = ["backupDelete"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof backupDelete>>,
    { params: BackupDeleteParams }
  > = (props) => {
    const { params } = props ?? {};

    return backupDelete(params, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type BackupDeleteMutationResult = NonNullable<
  Awaited<ReturnType<typeof backupDelete>>
>;

export type BackupDeleteMutationError = ErrorType<unknown>;

export const useBackupDelete = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof backupDelete>>,
      TError,
      { params: BackupDeleteParams },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof backupDelete>>,
  TError,
  { params: BackupDeleteParams },
  TContext
> => {
  return useMutation(getBackupDeleteMutationOptions(options), queryClient);
};
export type backupRestoreResponse200TextPlain = {
  data: DataDTO;
  status: 200;
};

export type backupRestoreResponse200ApplicationJson = {
  data: DataDTO;
  status: 200;
};

export type backupRestoreResponse200TextJson = {
  data: DataDTO;
  status: 200;
};

export type backupRestoreResponseSuccess = (
  | backupRestoreResponse200TextPlain
  | backupRestoreResponse200ApplicationJson
  | backupRestoreResponse200TextJson
) & {
  headers: Headers;
};
export const getBackupRestoreUrl = (params: BackupRestoreParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/backup/restore?${stringifiedParams}`
    : `/api/backup/restore`;
};

export const backupRestore = async (
  params: BackupRestoreParams,
  options?: RequestInit,
): Promise<backupRestoreResponseSuccess> => {
  return customInstance<backupRestoreResponseSuccess>(
    getBackupRestoreUrl(params),
    {
      ...options,
      method: "POST",
    },
  );
};

export const getBackupRestoreMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof backupRestore>>,
    TError,
    { params: BackupRestoreParams },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof backupRestore>>,
  TError,
  { params: BackupRestoreParams },
  TContext
> => {
  const mutationKey = ["backupRestore"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof backupRestore>>,
    { params: BackupRestoreParams }
  > = (props) => {
    const { params } = props ?? {};

    return backupRestore(params, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type BackupRestoreMutationResult = NonNullable<
  Awaited<ReturnType<typeof backupRestore>>
>;

export type BackupRestoreMutationError = ErrorType<unknown>;

export const useBackupRestore = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof backupRestore>>,
      TError,
      { params: BackupRestoreParams },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof backupRestore>>,
  TError,
  { params: BackupRestoreParams },
  TContext
> => {
  return useMutation(getBackupRestoreMutationOptions(options), queryClient);
};
