/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * PKVault API
 * OpenAPI spec version: 1.0.0
 */
import { useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type { WarningsDTO } from "../model";

import { customInstance } from "../../mutator/custom-instance";
import type { ErrorType } from "../../mutator/custom-instance";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export type warningsGetWarningsResponse200TextPlain = {
  data: WarningsDTO;
  status: 200;
};

export type warningsGetWarningsResponse200ApplicationJson = {
  data: WarningsDTO;
  status: 200;
};

export type warningsGetWarningsResponse200TextJson = {
  data: WarningsDTO;
  status: 200;
};

export type warningsGetWarningsResponseSuccess = (
  | warningsGetWarningsResponse200TextPlain
  | warningsGetWarningsResponse200ApplicationJson
  | warningsGetWarningsResponse200TextJson
) & {
  headers: Headers;
};
export const getWarningsGetWarningsUrl = () => {
  return `/api/warnings/warnings`;
};

export const warningsGetWarnings = async (
  options?: RequestInit,
): Promise<warningsGetWarningsResponseSuccess> => {
  return customInstance<warningsGetWarningsResponseSuccess>(
    getWarningsGetWarningsUrl(),
    {
      ...options,
      method: "GET",
    },
  );
};

export const getWarningsGetWarningsQueryKey = () => {
  return [`/api/warnings/warnings`] as const;
};

export const getWarningsGetWarningsQueryOptions = <
  TData = Awaited<ReturnType<typeof warningsGetWarnings>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof warningsGetWarnings>>,
      TError,
      TData
    >
  >;
  request?: SecondParameter<typeof customInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getWarningsGetWarningsQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof warningsGetWarnings>>
  > = ({ signal }) => warningsGetWarnings({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof warningsGetWarnings>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type WarningsGetWarningsQueryResult = NonNullable<
  Awaited<ReturnType<typeof warningsGetWarnings>>
>;
export type WarningsGetWarningsQueryError = ErrorType<unknown>;

export function useWarningsGetWarnings<
  TData = Awaited<ReturnType<typeof warningsGetWarnings>>,
  TError = ErrorType<unknown>,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof warningsGetWarnings>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof warningsGetWarnings>>,
          TError,
          Awaited<ReturnType<typeof warningsGetWarnings>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useWarningsGetWarnings<
  TData = Awaited<ReturnType<typeof warningsGetWarnings>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof warningsGetWarnings>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof warningsGetWarnings>>,
          TError,
          Awaited<ReturnType<typeof warningsGetWarnings>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useWarningsGetWarnings<
  TData = Awaited<ReturnType<typeof warningsGetWarnings>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof warningsGetWarnings>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useWarningsGetWarnings<
  TData = Awaited<ReturnType<typeof warningsGetWarnings>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof warningsGetWarnings>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getWarningsGetWarningsQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}
