/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * PKVault API
 * OpenAPI spec version: 1.0.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  DataDTO,
  SettingsDTO,
  SettingsGetSaveGlobsResultsParams,
  SettingsMutableDTO,
} from "../model";

import { customInstance } from "../../mutator/custom-instance";
import type { ErrorType } from "../../mutator/custom-instance";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export type settingsGetResponse200TextPlain = {
  data: SettingsDTO;
  status: 200;
};

export type settingsGetResponse200ApplicationJson = {
  data: SettingsDTO;
  status: 200;
};

export type settingsGetResponse200TextJson = {
  data: SettingsDTO;
  status: 200;
};

export type settingsGetResponseSuccess = (
  | settingsGetResponse200TextPlain
  | settingsGetResponse200ApplicationJson
  | settingsGetResponse200TextJson
) & {
  headers: Headers;
};
export const getSettingsGetUrl = () => {
  return `/api/settings`;
};

export const settingsGet = async (
  options?: RequestInit,
): Promise<settingsGetResponseSuccess> => {
  return customInstance<settingsGetResponseSuccess>(getSettingsGetUrl(), {
    ...options,
    method: "GET",
  });
};

export const getSettingsGetQueryKey = () => {
  return [`/api/settings`] as const;
};

export const getSettingsGetQueryOptions = <
  TData = Awaited<ReturnType<typeof settingsGet>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof settingsGet>>, TError, TData>
  >;
  request?: SecondParameter<typeof customInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getSettingsGetQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof settingsGet>>> = ({
    signal,
  }) => settingsGet({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof settingsGet>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type SettingsGetQueryResult = NonNullable<
  Awaited<ReturnType<typeof settingsGet>>
>;
export type SettingsGetQueryError = ErrorType<unknown>;

export function useSettingsGet<
  TData = Awaited<ReturnType<typeof settingsGet>>,
  TError = ErrorType<unknown>,
>(
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof settingsGet>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof settingsGet>>,
          TError,
          Awaited<ReturnType<typeof settingsGet>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useSettingsGet<
  TData = Awaited<ReturnType<typeof settingsGet>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof settingsGet>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof settingsGet>>,
          TError,
          Awaited<ReturnType<typeof settingsGet>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useSettingsGet<
  TData = Awaited<ReturnType<typeof settingsGet>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof settingsGet>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useSettingsGet<
  TData = Awaited<ReturnType<typeof settingsGet>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof settingsGet>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getSettingsGetQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

export type settingsEditResponse200TextPlain = {
  data: DataDTO;
  status: 200;
};

export type settingsEditResponse200ApplicationJson = {
  data: DataDTO;
  status: 200;
};

export type settingsEditResponse200TextJson = {
  data: DataDTO;
  status: 200;
};

export type settingsEditResponseSuccess = (
  | settingsEditResponse200TextPlain
  | settingsEditResponse200ApplicationJson
  | settingsEditResponse200TextJson
) & {
  headers: Headers;
};
export const getSettingsEditUrl = () => {
  return `/api/settings`;
};

export const settingsEdit = async (
  settingsMutableDTO: SettingsMutableDTO,
  options?: RequestInit,
): Promise<settingsEditResponseSuccess> => {
  return customInstance<settingsEditResponseSuccess>(getSettingsEditUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(settingsMutableDTO),
  });
};

export const getSettingsEditMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof settingsEdit>>,
    TError,
    { data: SettingsMutableDTO },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof settingsEdit>>,
  TError,
  { data: SettingsMutableDTO },
  TContext
> => {
  const mutationKey = ["settingsEdit"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof settingsEdit>>,
    { data: SettingsMutableDTO }
  > = (props) => {
    const { data } = props ?? {};

    return settingsEdit(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type SettingsEditMutationResult = NonNullable<
  Awaited<ReturnType<typeof settingsEdit>>
>;
export type SettingsEditMutationBody = SettingsMutableDTO;
export type SettingsEditMutationError = ErrorType<unknown>;

export const useSettingsEdit = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof settingsEdit>>,
      TError,
      { data: SettingsMutableDTO },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof settingsEdit>>,
  TError,
  { data: SettingsMutableDTO },
  TContext
> => {
  return useMutation(getSettingsEditMutationOptions(options), queryClient);
};
export type settingsGetSaveGlobsResultsResponse200TextPlain = {
  data: string[];
  status: 200;
};

export type settingsGetSaveGlobsResultsResponse200ApplicationJson = {
  data: string[];
  status: 200;
};

export type settingsGetSaveGlobsResultsResponse200TextJson = {
  data: string[];
  status: 200;
};

export type settingsGetSaveGlobsResultsResponseSuccess = (
  | settingsGetSaveGlobsResultsResponse200TextPlain
  | settingsGetSaveGlobsResultsResponse200ApplicationJson
  | settingsGetSaveGlobsResultsResponse200TextJson
) & {
  headers: Headers;
};
export const getSettingsGetSaveGlobsResultsUrl = (
  params?: SettingsGetSaveGlobsResultsParams,
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    const explodeParameters = ["globs"];

    if (Array.isArray(value) && explodeParameters.includes(key)) {
      value.forEach((v) => {
        normalizedParams.append(key, v === null ? "null" : v.toString());
      });
      return;
    }

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/settings/test-save-globs?${stringifiedParams}`
    : `/api/settings/test-save-globs`;
};

export const settingsGetSaveGlobsResults = async (
  params?: SettingsGetSaveGlobsResultsParams,
  options?: RequestInit,
): Promise<settingsGetSaveGlobsResultsResponseSuccess> => {
  return customInstance<settingsGetSaveGlobsResultsResponseSuccess>(
    getSettingsGetSaveGlobsResultsUrl(params),
    {
      ...options,
      method: "GET",
    },
  );
};

export const getSettingsGetSaveGlobsResultsQueryKey = (
  params?: SettingsGetSaveGlobsResultsParams,
) => {
  return [
    `/api/settings/test-save-globs`,
    ...(params ? [params] : []),
  ] as const;
};

export const getSettingsGetSaveGlobsResultsQueryOptions = <
  TData = Awaited<ReturnType<typeof settingsGetSaveGlobsResults>>,
  TError = ErrorType<unknown>,
>(
  params?: SettingsGetSaveGlobsResultsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof settingsGetSaveGlobsResults>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getSettingsGetSaveGlobsResultsQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof settingsGetSaveGlobsResults>>
  > = ({ signal }) =>
    settingsGetSaveGlobsResults(params, { signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof settingsGetSaveGlobsResults>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type SettingsGetSaveGlobsResultsQueryResult = NonNullable<
  Awaited<ReturnType<typeof settingsGetSaveGlobsResults>>
>;
export type SettingsGetSaveGlobsResultsQueryError = ErrorType<unknown>;

export function useSettingsGetSaveGlobsResults<
  TData = Awaited<ReturnType<typeof settingsGetSaveGlobsResults>>,
  TError = ErrorType<unknown>,
>(
  params: undefined | SettingsGetSaveGlobsResultsParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof settingsGetSaveGlobsResults>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof settingsGetSaveGlobsResults>>,
          TError,
          Awaited<ReturnType<typeof settingsGetSaveGlobsResults>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useSettingsGetSaveGlobsResults<
  TData = Awaited<ReturnType<typeof settingsGetSaveGlobsResults>>,
  TError = ErrorType<unknown>,
>(
  params?: SettingsGetSaveGlobsResultsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof settingsGetSaveGlobsResults>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof settingsGetSaveGlobsResults>>,
          TError,
          Awaited<ReturnType<typeof settingsGetSaveGlobsResults>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useSettingsGetSaveGlobsResults<
  TData = Awaited<ReturnType<typeof settingsGetSaveGlobsResults>>,
  TError = ErrorType<unknown>,
>(
  params?: SettingsGetSaveGlobsResultsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof settingsGetSaveGlobsResults>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useSettingsGetSaveGlobsResults<
  TData = Awaited<ReturnType<typeof settingsGetSaveGlobsResults>>,
  TError = ErrorType<unknown>,
>(
  params?: SettingsGetSaveGlobsResultsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof settingsGetSaveGlobsResults>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getSettingsGetSaveGlobsResultsQueryOptions(
    params,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}
