/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * PKVault API
 * OpenAPI spec version: 1.0.0
 */
import { useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  DexGetAll200One,
  DexGetAll200Three,
  DexGetAll200Two,
} from "../model";

import { customInstance } from "../../mutator/custom-instance";
import type { ErrorType } from "../../mutator/custom-instance";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export type dexGetAllResponse200TextPlain = {
  data: DexGetAll200One;
  status: 200;
};

export type dexGetAllResponse200ApplicationJson = {
  data: DexGetAll200Two;
  status: 200;
};

export type dexGetAllResponse200TextJson = {
  data: DexGetAll200Three;
  status: 200;
};

export type dexGetAllResponseSuccess = (
  | dexGetAllResponse200TextPlain
  | dexGetAllResponse200ApplicationJson
  | dexGetAllResponse200TextJson
) & {
  headers: Headers;
};
export const getDexGetAllUrl = () => {
  return `/api/dex`;
};

export const dexGetAll = async (
  options?: RequestInit,
): Promise<dexGetAllResponseSuccess> => {
  return customInstance<dexGetAllResponseSuccess>(getDexGetAllUrl(), {
    ...options,
    method: "GET",
  });
};

export const getDexGetAllQueryKey = () => {
  return [`/api/dex`] as const;
};

export const getDexGetAllQueryOptions = <
  TData = Awaited<ReturnType<typeof dexGetAll>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof dexGetAll>>, TError, TData>
  >;
  request?: SecondParameter<typeof customInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getDexGetAllQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof dexGetAll>>> = ({
    signal,
  }) => dexGetAll({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof dexGetAll>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type DexGetAllQueryResult = NonNullable<
  Awaited<ReturnType<typeof dexGetAll>>
>;
export type DexGetAllQueryError = ErrorType<unknown>;

export function useDexGetAll<
  TData = Awaited<ReturnType<typeof dexGetAll>>,
  TError = ErrorType<unknown>,
>(
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof dexGetAll>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof dexGetAll>>,
          TError,
          Awaited<ReturnType<typeof dexGetAll>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useDexGetAll<
  TData = Awaited<ReturnType<typeof dexGetAll>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof dexGetAll>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof dexGetAll>>,
          TError,
          Awaited<ReturnType<typeof dexGetAll>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useDexGetAll<
  TData = Awaited<ReturnType<typeof dexGetAll>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof dexGetAll>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useDexGetAll<
  TData = Awaited<ReturnType<typeof dexGetAll>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof dexGetAll>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getDexGetAllQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}
