/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * PKVault API
 * OpenAPI spec version: 1.0.0
 */
import type { BankView } from "./bankView.gen";

export type BankDTO = {
  id: string;
  idInt: number;
  name: string;
  isDefault: boolean;
  isExternal: boolean;
  order: number;
  view: BankView;
};
