/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * PKVault API
 * OpenAPI spec version: 1.0.0
 */
import type { BoxType } from "./boxType.gen";

export type BoxDTO = {
  id: string;
  type: BoxType;
  name: string;
  slotCount: number;
  order: number;
  bankId?: string;
  wallpaperName?: string;
  idInt: number;
  canSaveWrite: boolean;
  canSaveReceivePkm: boolean;
};
