/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * PKVault API
 * OpenAPI spec version: 1.0.0
 */

export type BoxType = (typeof BoxType)[keyof typeof BoxType];

export const BoxType = {
  Box: 0,
  SurpriseTrade: -42,
  PGL: -41,
  Scripted: -31,
  Pokéwalker: -11,
  BattleAgency: -10,
  Shiny: -9,
  Ride: -8,
  Resort: -7,
  Underground: -6,
  Fused: -5,
  GTS: -4,
  Daycare: -3,
  BattleBox: -2,
  Party: -1,
} as const;
