/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * PKVault API
 * OpenAPI spec version: 1.0.0
 */
import type { PkmVariantDTO } from "./pkmVariantDTO.gen";

export type DataDTOStateOfDictionaryOfStringAndPkmVariantDTOData = {
  [key: string]: PkmVariantDTO;
};
