/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * PKVault API
 * OpenAPI spec version: 1.0.0
 */
import type { BoxDTO } from "./boxDTO.gen";
import type { DataDTOStateOfDictionaryOfStringAndPkmLegalityDTO } from "./dataDTOStateOfDictionaryOfStringAndPkmLegalityDTO.gen";
import type { DataDTOStateOfDictionaryOfStringAndPkmSaveDTO } from "./dataDTOStateOfDictionaryOfStringAndPkmSaveDTO.gen";

export type DataSaveDTO = {
  saveId: number;
  saveBoxes?: BoxDTO[];
  savePkms?: DataDTOStateOfDictionaryOfStringAndPkmSaveDTO;
  savePkmLegality?: DataDTOStateOfDictionaryOfStringAndPkmLegalityDTO;
};
