/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * PKVault API
 * OpenAPI spec version: 1.0.0
 */

export type DataDTOType = (typeof DataDTOType)[keyof typeof DataDTOType];

export const DataDTOType = {
  DATA_DTO: 1,
} as const;
