/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * PKVault API
 * OpenAPI spec version: 1.0.0
 */
import type { BackupDTO } from "./backupDTO.gen";
import type { DataActionPayload } from "./dataActionPayload.gen";
import type { DataDTOSaveInfos } from "./dataDTOSaveInfos.gen";
import type { DataDTOStateOfDictionaryOfStringAndBankDTO } from "./dataDTOStateOfDictionaryOfStringAndBankDTO.gen";
import type { DataDTOStateOfDictionaryOfStringAndBoxDTO } from "./dataDTOStateOfDictionaryOfStringAndBoxDTO.gen";
import type { DataDTOStateOfDictionaryOfStringAndPkmLegalityDTO } from "./dataDTOStateOfDictionaryOfStringAndPkmLegalityDTO.gen";
import type { DataDTOStateOfDictionaryOfStringAndPkmVariantDTO } from "./dataDTOStateOfDictionaryOfStringAndPkmVariantDTO.gen";
import type { DataDTOStateOfDictionaryOfUInt16AndDictionaryOfUInt32AndDexItemDTO } from "./dataDTOStateOfDictionaryOfUInt16AndDictionaryOfUInt32AndDexItemDTO.gen";
import type { DataDTOType } from "./dataDTOType.gen";
import type { DataSaveDTO } from "./dataSaveDTO.gen";
import type { SettingsDTO } from "./settingsDTO.gen";
import type { StaticDataDTO } from "./staticDataDTO.gen";
import type { WarningsDTO } from "./warningsDTO.gen";

export type DataDTO = {
  staticData?: StaticDataDTO;
  mainBanks?: DataDTOStateOfDictionaryOfStringAndBankDTO;
  mainBoxes?: DataDTOStateOfDictionaryOfStringAndBoxDTO;
  mainPkmVariants?: DataDTOStateOfDictionaryOfStringAndPkmVariantDTO;
  mainPkmLegalities?: DataDTOStateOfDictionaryOfStringAndPkmLegalityDTO;
  dex?: DataDTOStateOfDictionaryOfUInt16AndDictionaryOfUInt32AndDexItemDTO;
  saves?: DataSaveDTO[];
  invalidateAllSaves: boolean;
  actions?: DataActionPayload[];
  warnings?: WarningsDTO;
  saveInfos?: DataDTOSaveInfos;
  backups?: BackupDTO[];
  settings?: SettingsDTO;
  type: DataDTOType;
};
