/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * PKVault API
 * OpenAPI spec version: 1.0.0
 */
import type { BankDTO } from "./bankDTO.gen";

export type DataDTOStateOfDictionaryOfStringAndBankDTOData = {
  [key: string]: BankDTO;
};
