/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * PKVault API
 * OpenAPI spec version: 1.0.0
 */
import type { DataDTOStateOfDictionaryOfUInt16AndDictionaryOfUInt32AndDexItemDTOData } from "./dataDTOStateOfDictionaryOfUInt16AndDictionaryOfUInt32AndDexItemDTOData.gen";

export type DataDTOStateOfDictionaryOfUInt16AndDictionaryOfUInt32AndDexItemDTO =
  {
    all: boolean;
    data?: DataDTOStateOfDictionaryOfUInt16AndDictionaryOfUInt32AndDexItemDTOData;
  };
