/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * PKVault API
 * OpenAPI spec version: 1.0.0
 */
import type { PkmLegalityDTO } from "./pkmLegalityDTO.gen";

export type DataDTOStateOfDictionaryOfStringAndPkmLegalityDTOData = {
  [key: string]: PkmLegalityDTO;
};
