/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * PKVault API
 * OpenAPI spec version: 1.0.0
 */

export type DataActionType =
  (typeof DataActionType)[keyof typeof DataActionType];

export const DataActionType = {
  MAIN_CREATE_BANK: 0,
  MAIN_UPDATE_BANK: 1,
  MAIN_DELETE_BANK: 2,
  MAIN_CREATE_BOX: 3,
  MAIN_UPDATE_BOX: 4,
  MAIN_DELETE_BOX: 5,
  MAIN_CREATE_PKM_VERSION: 6,
  MOVE_PKM: 7,
  DETACH_PKM_SAVE: 8,
  DELETE_PKM_VERSION: 9,
  EDIT_PKM_VERSION: 10,
  EDIT_PKM_SAVE: 11,
  SAVE_DELETE_PKM: 12,
  PKM_SYNCHRONIZE: 13,
  EVOLVE_PKM: 14,
  SORT_PKM: 15,
  DEX_SYNC: 16,
  DATA_NORMALIZE: 17,
  UPDATE_EXTERNAL_PKM: 18,
} as const;
