/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * PKVault API
 * OpenAPI spec version: 1.0.0
 */
import type { DataDTOStateOfDictionaryOfStringAndBankDTOData } from "./dataDTOStateOfDictionaryOfStringAndBankDTOData.gen";

export type DataDTOStateOfDictionaryOfStringAndBankDTO = {
  all: boolean;
  data?: DataDTOStateOfDictionaryOfStringAndBankDTOData;
};
