/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * PKVault API
 * OpenAPI spec version: 1.0.0
 */
import type { DataDTOStateOfDictionaryOfStringAndBoxDTOData } from "./dataDTOStateOfDictionaryOfStringAndBoxDTOData.gen";

export type DataDTOStateOfDictionaryOfStringAndBoxDTO = {
  all: boolean;
  data?: DataDTOStateOfDictionaryOfStringAndBoxDTOData;
};
