/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * PKVault API
 * OpenAPI spec version: 1.0.0
 */
import type { DataActionType } from "./dataActionType.gen";

export type DataActionPayload = {
  type: DataActionType;
  parameters: unknown[];
};
