/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * PKVault API
 * OpenAPI spec version: 1.0.0
 */
import type { DexItemDTO } from "./dexItemDTO.gen";

export type DexGetAll200Three = {
  [key: string]: { [key: string]: DexItemDTO };
};
