/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * PKVault API
 * OpenAPI spec version: 1.0.0
 */
import type { DexItemForm } from "./dexItemForm.gen";
import type { LanguageID } from "./languageID.gen";

export type DexItemDTO = {
  id: string;
  species: number;
  saveId: number;
  forms: DexItemForm[];
  languages: LanguageID[];
};
