/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * PKVault API
 * OpenAPI spec version: 1.0.0
 */
import type { EntityContext } from "./entityContext.gen";
import type { Gender } from "./gender.gen";

export type DexItemForm = {
  id: string;
  species: number;
  form: number;
  gender: Gender;
  types: number[];
  abilities: number[];
  baseStats: number[];
  isSeen: boolean;
  isSeenShiny: boolean;
  isSeenAlpha: boolean;
  isCaught: boolean;
  isOwned: boolean;
  isOwnedShiny: boolean;
  context: EntityContext;
  generation: number;
};
