/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * PKVault API
 * OpenAPI spec version: 1.0.0
 */

export type EntityContext = (typeof EntityContext)[keyof typeof EntityContext];

export const EntityContext = {
  None: 0,
  Gen1: 1,
  Gen2: 2,
  Gen3: 3,
  Gen4: 4,
  Gen5: 5,
  Gen6: 6,
  Gen7: 7,
  Gen8: 8,
  Gen9: 9,
  SplitInvalid: 10,
  Gen7b: 11,
  Gen8a: 12,
  Gen8b: 13,
  Gen9a: 14,
  MaxInvalid: 15,
} as const;
