/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * PKVault API
 * OpenAPI spec version: 1.0.0
 */

export type Gender = (typeof Gender)[keyof typeof Gender];

export const Gender = {
  Male: 0,
  Female: 1,
  Genderless: 2,
} as const;
