/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * PKVault API
 * OpenAPI spec version: 1.0.0
 */

export type LanguageID = (typeof LanguageID)[keyof typeof LanguageID];

export const LanguageID = {
  None: 0,
  Japanese: 1,
  English: 2,
  French: 3,
  Italian: 4,
  German: 5,
  UNUSED_6: 6,
  Spanish: 7,
  Korean: 8,
  ChineseS: 9,
  ChineseT: 10,
  SpanishL: 11,
} as const;
