/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * PKVault API
 * OpenAPI spec version: 1.0.0
 */

export type MarkingColorUniversal =
  (typeof MarkingColorUniversal)[keyof typeof MarkingColorUniversal];

export const MarkingColorUniversal = {
  NotMarked: 0,
  Marked: 1,
  MarkedBlue: 2,
  MarkedPink: 3,
} as const;
