/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * PKVault API
 * OpenAPI spec version: 1.0.0
 */

export type MoveCategory = (typeof MoveCategory)[keyof typeof MoveCategory];

export const MoveCategory = {
  PHYSICAL: 0,
  SPECIAL: 1,
  STATUS: 2,
} as const;
