/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * PKVault API
 * OpenAPI spec version: 1.0.0
 */

export type PKMLoadError = (typeof PKMLoadError)[keyof typeof PKMLoadError];

export const PKMLoadError = {
  UNKNOWN: 0,
  NOT_LOADED: 1,
  NOT_FOUND: 2,
  TOO_SMALL: 3,
  TOO_BIG: 4,
  UNAUTHORIZED: 5,
} as const;
