/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * PKVault API
 * OpenAPI spec version: 1.0.0
 */
import type { PkmBaseDTO } from "./pkmBaseDTO.gen";

export type PkmSaveDTO = PkmBaseDTO & {
  idBase: string;
  saveId: number;
  team: number;
  isLocked: boolean;
  party: number;
  isStarter: boolean;
  canMove: boolean;
  canDelete: boolean;
  canEdit: boolean;
  canMoveToSave: boolean;
  canMoveToMain: boolean;
  canMoveAttachedToMain: boolean;
};
