/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * PKVault API
 * OpenAPI spec version: 1.0.0
 */
import type { GameVersion } from "./gameVersion.gen";
import type { PkmBaseDTO } from "./pkmBaseDTO.gen";

export type PkmVariantDTO = PkmBaseDTO & {
  isMain: boolean;
  isExternal: boolean;
  attachedSaveId?: number;
  attachedSavePkmIdBase?: string;
  isFilePresent: boolean;
  filepath: string;
  filepathAbsolute: string;
  canMoveAttachedToSave: boolean;
  canDelete: boolean;
  canMoveToSave: boolean;
  canEdit: boolean;
  canEvolve: boolean;
  canCreateVariant: boolean;
  compatibleWithVersions: GameVersion[];
};
