/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * PKVault API
 * OpenAPI spec version: 1.0.0
 */
import type { EntityContext } from "./entityContext.gen";
import type { GameVersion } from "./gameVersion.gen";
import type { Gender } from "./gender.gen";
import type { LanguageID } from "./languageID.gen";

export type SaveInfosDTO = {
  id: number;
  lastWriteTime: string;
  displayedVersion: GameVersion;
  version: GameVersion;
  context: EntityContext;
  generation: number;
  tid: number;
  sid?: number;
  language: LanguageID;
  playTime: string;
  trainerGender: Gender;
  trainerName: string;
  dexSeenCount: number;
  dexCaughtCount: number;
  ownedCount: number;
  shinyCount: number;
  partyCount: number;
  daycareCount: number;
  boxCount: number;
  boxSlotCount: number;
  path: string;
};
