/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * PKVault API
 * OpenAPI spec version: 1.0.0
 */
import type { SettingsMutableDTO } from "./settingsMutableDTO.gen";

export type SettingsDTO = {
  buildID: string;
  version: string;
  pkhexVersion: string;
  appDirectory: string;
  settingsPath: string;
  userId: string;
  canUpdateSettings: boolean;
  canScanSaves: boolean;
  settingsMutable: SettingsMutableDTO;
};
