/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * PKVault API
 * OpenAPI spec version: 1.0.0
 */
import type { GameVersion } from "./gameVersion.gen";

export type SettingsMutableDTOSavEVERSIONOVERRIDES = {
  [key: string]: GameVersion;
};
