/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * PKVault API
 * OpenAPI spec version: 1.0.0
 */
import type { SettingsMutableDTOSavEVERSIONOVERRIDES } from "./settingsMutableDTOSavEVERSIONOVERRIDES.gen";

export type SettingsMutableDTO = {
  dB_PATH: string;
  savE_GLOBS: string[];
  pkM_EXTERNAL_GLOBS?: string[];
  storagE_PATH: string;
  backuP_PATH: string;
  hidE_CHEATS: boolean;
  skiP_LEGALITY_CHECKS: boolean;
  savE_VERSION_OVERRIDES?: SettingsMutableDTOSavEVERSIONOVERRIDES;
  httpS_NOCERT?: boolean;
  httpS_CERT_PEM_PATH?: string;
  httpS_KEY_PEM_PATH?: string;
  language?: string;
};
