/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * PKVault API
 * OpenAPI spec version: 1.0.0
 */

export type SpriteInfo = {
  sheetName: string;
  x: number;
  y: number;
  width: number;
  height: number;
};
