/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * PKVault API
 * OpenAPI spec version: 1.0.0
 */
import type { StaticDataDTOAbilities } from "./staticDataDTOAbilities.gen";
import type { StaticDataDTOGenerations } from "./staticDataDTOGenerations.gen";
import type { StaticDataDTOLanguages } from "./staticDataDTOLanguages.gen";
import type { StaticDataDTOMoves } from "./staticDataDTOMoves.gen";
import type { StaticDataDTONatures } from "./staticDataDTONatures.gen";
import type { StaticDataDTOPokedexes } from "./staticDataDTOPokedexes.gen";
import type { StaticDataDTORibbons } from "./staticDataDTORibbons.gen";
import type { StaticDataDTOStats } from "./staticDataDTOStats.gen";
import type { StaticDataDTOTypes } from "./staticDataDTOTypes.gen";
import type { StaticDataDTOVersions } from "./staticDataDTOVersions.gen";
import type { StaticEvolvesData } from "./staticEvolvesData.gen";
import type { StaticItemsData } from "./staticItemsData.gen";
import type { StaticSpeciesData } from "./staticSpeciesData.gen";
import type { StaticSpritesheetsData } from "./staticSpritesheetsData.gen";

export type StaticDataDTO = {
  versions: StaticDataDTOVersions;
  species: StaticSpeciesData;
  stats: StaticDataDTOStats;
  types: StaticDataDTOTypes;
  moves: StaticDataDTOMoves;
  natures: StaticDataDTONatures;
  abilities: StaticDataDTOAbilities;
  items: StaticItemsData;
  evolves: StaticEvolvesData;
  generations: StaticDataDTOGenerations;
  pokedexes: StaticDataDTOPokedexes;
  ribbons: StaticDataDTORibbons;
  languages: StaticDataDTOLanguages;
  spritesheets: StaticSpritesheetsData;
  eggSprite: string;
};
