/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * PKVault API
 * OpenAPI spec version: 1.0.0
 */
import type { StaticEvolveOther } from "./staticEvolveOther.gen";
import type { StaticEvolveTrade } from "./staticEvolveTrade.gen";
import type { StaticEvolveTradeWithItem } from "./staticEvolveTradeWithItem.gen";

export type StaticEvolve = {
  species: number;
  trade: StaticEvolveTrade;
  tradeWithItem: StaticEvolveTradeWithItem;
  other: StaticEvolveOther;
  previousSpecies?: number;
};
