/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * PKVault API
 * OpenAPI spec version: 1.0.0
 */
import type { MoveCategory } from "./moveCategory.gen";

export type StaticMoveGeneration = {
  untilGeneration: number;
  type: number;
  category: MoveCategory;
  power?: number;
};
