/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * PKVault API
 * OpenAPI spec version: 1.0.0
 */
import type { StaticSpecies } from "./staticSpecies.gen";

export type StaticSpeciesData = { [key: string]: StaticSpecies };
