/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * PKVault API
 * OpenAPI spec version: 1.0.0
 */
import type { StaticItem } from "./staticItem.gen";

export type StaticItemsDataItems = { [key: string]: StaticItem };
