/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * PKVault API
 * OpenAPI spec version: 1.0.0
 */
import type { StaticSpritesheetsDataItems } from "./staticSpritesheetsDataItems.gen";
import type { StaticSpritesheetsDataSpecies } from "./staticSpritesheetsDataSpecies.gen";

export type StaticSpritesheetsData = {
  species: StaticSpritesheetsDataSpecies;
  items: StaticSpritesheetsDataItems;
};
