/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * PKVault API
 * OpenAPI spec version: 1.0.0
 */

export type StaticSpeciesForm = {
  id: number;
  name: string;
  spriteDefault: string;
  spriteFemale?: string;
  spriteShiny: string;
  spriteShinyFemale?: string;
  spriteShadow?: string;
  hasGenderDifferences: boolean;
  isBattleOnly: boolean;
};
