/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * PKVault API
 * OpenAPI spec version: 1.0.0
 */
import type { StaticPokedex } from "./staticPokedex.gen";

export type StaticDataDTOPokedexes = { [key: string]: StaticPokedex };
