/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * PKVault API
 * OpenAPI spec version: 1.0.0
 */
import type { StaticStat } from "./staticStat.gen";

export type StaticDataDTOStats = { [key: string]: StaticStat };
