/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * PKVault API
 * OpenAPI spec version: 1.0.0
 */
import type { StaticPokedexPokemonIndexes } from "./staticPokedexPokemonIndexes.gen";

export type StaticPokedex = {
  key: string;
  name: string;
  order: number;
  pokemonIndexes: StaticPokedexPokemonIndexes;
};
