/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * PKVault API
 * OpenAPI spec version: 1.0.0
 */
import type { StaticItemsDataItems } from "./staticItemsDataItems.gen";
import type { StaticVersionsItems } from "./staticVersionsItems.gen";

export type StaticItemsData = {
  versionItems: StaticVersionsItems[];
  items: StaticItemsDataItems;
};
