/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * PKVault API
 * OpenAPI spec version: 1.0.0
 */
import type { Gender } from "./gender.gen";
import type { StaticSpeciesForms } from "./staticSpeciesForms.gen";
import type { StaticSpeciesPokedexIndexes } from "./staticSpeciesPokedexIndexes.gen";

export type StaticSpecies = {
  id: number;
  generation: number;
  genders: Gender[];
  forms: StaticSpeciesForms;
  pokedexIndexes: StaticSpeciesPokedexIndexes;
};
