/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * PKVault API
 * OpenAPI spec version: 1.0.0
 */

export type StaticNature = {
  id: number;
  name: string;
  increasedStatIndex?: number;
  decreasedStatIndex?: number;
};
