/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * PKVault API
 * OpenAPI spec version: 1.0.0
 */
import type { EntityContext } from "./entityContext.gen";
import type { GameVersion } from "./gameVersion.gen";

export type StaticVersion = {
  id: number;
  name: string;
  context: EntityContext;
  isGameVersion: boolean;
  children: GameVersion[];
  generation: number;
  region: string[];
  pokedexes: string[];
  maxSpeciesId: number;
  maxIV: number;
  maxEV: number;
};
