/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * PKVault API
 * OpenAPI spec version: 1.0.0
 */

export type StorageUpdateMainBoxType =
  (typeof StorageUpdateMainBoxType)[keyof typeof StorageUpdateMainBoxType];

export const StorageUpdateMainBoxType = {
  NUMBER_0: 0,
  NUMBER_MINUS_42: -42,
  NUMBER_MINUS_41: -41,
  NUMBER_MINUS_31: -31,
  NUMBER_MINUS_11: -11,
  NUMBER_MINUS_10: -10,
  NUMBER_MINUS_9: -9,
  NUMBER_MINUS_8: -8,
  NUMBER_MINUS_7: -7,
  NUMBER_MINUS_6: -6,
  NUMBER_MINUS_5: -5,
  NUMBER_MINUS_4: -4,
  NUMBER_MINUS_3: -3,
  NUMBER_MINUS_2: -2,
  NUMBER_MINUS_1: -1,
} as const;
