/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * PKVault API
 * OpenAPI spec version: 1.0.0
 */
import type { StorageMainCreatePkmVariantContext } from "./storageMainCreatePkmVariantContext.gen";

export type StorageMainCreatePkmVariantParams = {
  pkmVariantId: string;
  context: StorageMainCreatePkmVariantContext;
};
