/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * PKVault API
 * OpenAPI spec version: 1.0.0
 */
import type { StorageUpdateMainBoxType } from "./storageUpdateMainBoxType.gen";

export type StorageUpdateMainBoxParams = {
  boxName: string;
  order: number;
  bankId: string;
  slotCount: number;
  type: StorageUpdateMainBoxType;
};
