/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * PKVault API
 * OpenAPI spec version: 1.0.0
 */
import type { PkmVariantWarning } from "./pkmVariantWarning.gen";
import type { SaveChangedWarning } from "./saveChangedWarning.gen";
import type { SaveDuplicateWarning } from "./saveDuplicateWarning.gen";

export type WarningsDTO = {
  saveChangedWarnings: SaveChangedWarning[];
  pkmVariantWarnings: PkmVariantWarning[];
  saveDuplicateWarnings: SaveDuplicateWarning[];
  warningsCount: number;
};
