/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StorageRouteImport } from './routes/storage'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SavesRouteImport } from './routes/saves'
import { Route as PokedexRouteImport } from './routes/pokedex'
import { Route as IndexRouteImport } from './routes/index'

const StorageRoute = StorageRouteImport.update({
  id: '/storage',
  path: '/storage',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SavesRoute = SavesRouteImport.update({
  id: '/saves',
  path: '/saves',
  getParentRoute: () => rootRouteImport,
} as any)
const PokedexRoute = PokedexRouteImport.update({
  id: '/pokedex',
  path: '/pokedex',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/pokedex': typeof PokedexRoute
  '/saves': typeof SavesRoute
  '/settings': typeof SettingsRoute
  '/storage': typeof StorageRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/pokedex': typeof PokedexRoute
  '/saves': typeof SavesRoute
  '/settings': typeof SettingsRoute
  '/storage': typeof StorageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/pokedex': typeof PokedexRoute
  '/saves': typeof SavesRoute
  '/settings': typeof SettingsRoute
  '/storage': typeof StorageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/pokedex' | '/saves' | '/settings' | '/storage'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/pokedex' | '/saves' | '/settings' | '/storage'
  id: '__root__' | '/' | '/pokedex' | '/saves' | '/settings' | '/storage'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PokedexRoute: typeof PokedexRoute
  SavesRoute: typeof SavesRoute
  SettingsRoute: typeof SettingsRoute
  StorageRoute: typeof StorageRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/storage': {
      id: '/storage'
      path: '/storage'
      fullPath: '/storage'
      preLoaderRoute: typeof StorageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saves': {
      id: '/saves'
      path: '/saves'
      fullPath: '/saves'
      preLoaderRoute: typeof SavesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pokedex': {
      id: '/pokedex'
      path: '/pokedex'
      fullPath: '/pokedex'
      preLoaderRoute: typeof PokedexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PokedexRoute: PokedexRoute,
  SavesRoute: SavesRoute,
  SettingsRoute: SettingsRoute,
  StorageRoute: StorageRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
