/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * PKVault API
 * OpenAPI spec version: 1.0.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  DataDTO,
  SaveInfosGetAll200One,
  SaveInfosGetAll200Three,
  SaveInfosGetAll200Two,
} from "../model";

import { customInstance } from "../../mutator/custom-instance";
import type { ErrorType } from "../../mutator/custom-instance";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export type saveInfosGetAllResponse200TextPlain = {
  data: SaveInfosGetAll200One;
  status: 200;
};

export type saveInfosGetAllResponse200ApplicationJson = {
  data: SaveInfosGetAll200Two;
  status: 200;
};

export type saveInfosGetAllResponse200TextJson = {
  data: SaveInfosGetAll200Three;
  status: 200;
};

export type saveInfosGetAllResponseSuccess = (
  | saveInfosGetAllResponse200TextPlain
  | saveInfosGetAllResponse200ApplicationJson
  | saveInfosGetAllResponse200TextJson
) & {
  headers: Headers;
};
export const getSaveInfosGetAllUrl = () => {
  return `/api/save-infos`;
};

export const saveInfosGetAll = async (
  options?: RequestInit,
): Promise<saveInfosGetAllResponseSuccess> => {
  return customInstance<saveInfosGetAllResponseSuccess>(
    getSaveInfosGetAllUrl(),
    {
      ...options,
      method: "GET",
    },
  );
};

export const getSaveInfosGetAllQueryKey = () => {
  return [`/api/save-infos`] as const;
};

export const getSaveInfosGetAllQueryOptions = <
  TData = Awaited<ReturnType<typeof saveInfosGetAll>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof saveInfosGetAll>>, TError, TData>
  >;
  request?: SecondParameter<typeof customInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getSaveInfosGetAllQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof saveInfosGetAll>>> = ({
    signal,
  }) => saveInfosGetAll({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof saveInfosGetAll>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type SaveInfosGetAllQueryResult = NonNullable<
  Awaited<ReturnType<typeof saveInfosGetAll>>
>;
export type SaveInfosGetAllQueryError = ErrorType<unknown>;

export function useSaveInfosGetAll<
  TData = Awaited<ReturnType<typeof saveInfosGetAll>>,
  TError = ErrorType<unknown>,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof saveInfosGetAll>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof saveInfosGetAll>>,
          TError,
          Awaited<ReturnType<typeof saveInfosGetAll>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useSaveInfosGetAll<
  TData = Awaited<ReturnType<typeof saveInfosGetAll>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof saveInfosGetAll>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof saveInfosGetAll>>,
          TError,
          Awaited<ReturnType<typeof saveInfosGetAll>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useSaveInfosGetAll<
  TData = Awaited<ReturnType<typeof saveInfosGetAll>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof saveInfosGetAll>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useSaveInfosGetAll<
  TData = Awaited<ReturnType<typeof saveInfosGetAll>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof saveInfosGetAll>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getSaveInfosGetAllQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

export type saveInfosScanResponse200TextPlain = {
  data: DataDTO;
  status: 200;
};

export type saveInfosScanResponse200ApplicationJson = {
  data: DataDTO;
  status: 200;
};

export type saveInfosScanResponse200TextJson = {
  data: DataDTO;
  status: 200;
};

export type saveInfosScanResponseSuccess = (
  | saveInfosScanResponse200TextPlain
  | saveInfosScanResponse200ApplicationJson
  | saveInfosScanResponse200TextJson
) & {
  headers: Headers;
};
export const getSaveInfosScanUrl = () => {
  return `/api/save-infos`;
};

export const saveInfosScan = async (
  options?: RequestInit,
): Promise<saveInfosScanResponseSuccess> => {
  return customInstance<saveInfosScanResponseSuccess>(getSaveInfosScanUrl(), {
    ...options,
    method: "PUT",
  });
};

export const getSaveInfosScanMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof saveInfosScan>>,
    TError,
    void,
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof saveInfosScan>>,
  TError,
  void,
  TContext
> => {
  const mutationKey = ["saveInfosScan"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof saveInfosScan>>,
    void
  > = () => {
    return saveInfosScan(requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type SaveInfosScanMutationResult = NonNullable<
  Awaited<ReturnType<typeof saveInfosScan>>
>;

export type SaveInfosScanMutationError = ErrorType<unknown>;

export const useSaveInfosScan = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof saveInfosScan>>,
      TError,
      void,
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof saveInfosScan>>,
  TError,
  void,
  TContext
> => {
  return useMutation(getSaveInfosScanMutationOptions(options), queryClient);
};
export type saveInfosDownloadResponse200 = {
  data: Blob;
  status: 200;
};

export type saveInfosDownloadResponseSuccess = saveInfosDownloadResponse200 & {
  headers: Headers;
};
export const getSaveInfosDownloadUrl = (saveId: number) => {
  return `/api/save-infos/${saveId}/download`;
};

export const saveInfosDownload = async (
  saveId: number,
  options?: RequestInit,
): Promise<saveInfosDownloadResponseSuccess> => {
  return customInstance<saveInfosDownloadResponseSuccess>(
    getSaveInfosDownloadUrl(saveId),
    {
      ...options,
      method: "GET",
    },
  );
};

export const getSaveInfosDownloadQueryKey = (saveId: number) => {
  return [`/api/save-infos/${saveId}/download`] as const;
};

export const getSaveInfosDownloadQueryOptions = <
  TData = Awaited<ReturnType<typeof saveInfosDownload>>,
  TError = ErrorType<unknown>,
>(
  saveId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof saveInfosDownload>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getSaveInfosDownloadQueryKey(saveId);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof saveInfosDownload>>
  > = ({ signal }) => saveInfosDownload(saveId, { signal, ...requestOptions });

  return {
    queryKey,
    queryFn,
    enabled: !!saveId,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof saveInfosDownload>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type SaveInfosDownloadQueryResult = NonNullable<
  Awaited<ReturnType<typeof saveInfosDownload>>
>;
export type SaveInfosDownloadQueryError = ErrorType<unknown>;

export function useSaveInfosDownload<
  TData = Awaited<ReturnType<typeof saveInfosDownload>>,
  TError = ErrorType<unknown>,
>(
  saveId: number,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof saveInfosDownload>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof saveInfosDownload>>,
          TError,
          Awaited<ReturnType<typeof saveInfosDownload>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useSaveInfosDownload<
  TData = Awaited<ReturnType<typeof saveInfosDownload>>,
  TError = ErrorType<unknown>,
>(
  saveId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof saveInfosDownload>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof saveInfosDownload>>,
          TError,
          Awaited<ReturnType<typeof saveInfosDownload>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useSaveInfosDownload<
  TData = Awaited<ReturnType<typeof saveInfosDownload>>,
  TError = ErrorType<unknown>,
>(
  saveId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof saveInfosDownload>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useSaveInfosDownload<
  TData = Awaited<ReturnType<typeof saveInfosDownload>>,
  TError = ErrorType<unknown>,
>(
  saveId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof saveInfosDownload>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getSaveInfosDownloadQueryOptions(saveId, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}
